/*
 * channels.h — PMU channel table for the simulator
 *
 * ============================================================
 *  GENERATED by 05-PROCESS/tools/gen.py from 02-HARNESS/data/pmu_pins.csv
 *  Do not edit here. Put measured figures in the CSV (meas_a / soft_fuse)
 *  and re-run gen.py: this file, CHANNEL-SCHEDULE.md, SPEC.md and the
 *  PIN-MAP all update together. That is the whole point.
 * ============================================================
 *
 * Units: 0.01 A, matching CAN 0x130 and cluster_core.h.
 * inrush: multiplier x10 applied for inrushMs after switch-on.
 * limit:  measured soft fuse where one exists (D-164/165); otherwise a
 *         provisional bench value derived from the estimate. The real
 *         PMU output stays DISABLED until measured — this table only
 *         drives the simulator and the diagnostics page.
 */

#ifndef CHANNELS_H
#define CHANNELS_H

#include <stdint.h>

enum ChSrc : uint8_t { EST = 0, MEASURED = 1, DEAD = 2, RESERVED = 3 };

struct ChannelSpec {
    const char *name;
    uint16_t    steady;      /* 0.01 A                        */
    uint16_t    limit;       /* 0.01 A soft fuse, provisional */
    uint8_t     inrushX10;   /* multiplier x10 -> 100 = 10.0x */
    uint16_t    inrushMs;
    ChSrc       src;
};

/* ---- O1..O24 ---- */
static const ChannelSpec CH[24] = {
/*  name            steady  limit  inX10   ms   source      */
  { "MOTOR BUS",        950,   2500,   70,  400, EST      }, /* O1   INTERIM fuse 25 */
  { "HEAD LOW",         300,   2500,   15,   80, EST      }, /* O2   INTERIM fuse 25 */
  { "HEAD HIGH",        350,   2500,   15,   80, EST      }, /* O3   INTERIM fuse 25 */
  { "DEFOG",           1150,   2500,   13, 2000, EST      }, /* O4   INTERIM fuse 25 */
  { "FUEL PUMP",        238,    400,   30,  150, MEASURED }, /* O5   MEASURED 2026-08 — 2 */
  { "TAIL PARK",        540,    750,  100,   40, MEASURED }, /* O6   MEASURED 2026-08 — 5 */
  { "BRAKE",            700,    950,  100,   40, MEASURED }, /* O7   MEASURED 2026-08 (D-165) */
  { "WIPE LOW",         400,   1500,   70,  300, EST      }, /* O8   INTERIM fuse 15 */
  { "WIPE HIGH",        550,   1500,   70,  300, EST      }, /* O9   INTERIM fuse 15 */
  { "ACCESSORY",        250,   1500,   20,  100, EST      }, /* O10  INTERIM fuse 15 */
  { "HORN",             600,   1500,   30,   80, EST      }, /* O11  INTERIM fuse 15 */
  { "IGNITION",         500,   2500,   20,  100, EST      }, /* O12  INTERIM fuse 25 */
  { "LS ECU",             0,   1800,   10,    0, RESERVED }, /* O13  D-007 */
  { "LS FAN",             0,   2500,   80,  500, RESERVED }, /* O14  D-007 */
  { "COMFORT",         1400,   2000,   15,  200, EST      }, /* O15  Loads themselves are deferre */
  { "BLOWER",             0,   2000,   80,  600, DEAD     }, /* O16  ⚡ flyback */
  { "TURN L",           340,    450,  100,   40, MEASURED }, /* O17  MEASURED 2026-08 */
  { "TURN R",           340,    450,  100,   40, MEASURED }, /* O18  MEASURED 2026-08 */
  { "REVERSE",          390,    700,  100,   40, EST      }, /* O19  INTERIM fuse 7 */
  { "INTERIOR",         250,    700,  100,   40, EST      }, /* O20  INTERIM fuse 7 */
  { "START RLY",         20,    700,   20,   50, EST      }, /* O21  INTERIM fuse 7 */
  { "KEEP ALIVE",        15,    700,   10,    0, EST      }, /* O22  INTERIM fuse 7 */
  { "A15 IN",             0,    700,   10,    0, RESERVED }, /* A15  Occupies O23 */
  { "A16 IN",             0,    700,   10,    0, RESERVED }, /* A16  Occupies O24 */
};

/* Channel indices, so the model reads like the schedule rather than
 * like an array of magic numbers. O23/O24 are configured as inputs A15/A16. */
enum {
  O1_MOTOR, O2_HEAD_LO, O3_HEAD_HI, O4_DEFOG, O5_FUEL, O6_TAIL,
  O7_BRAKE, O8_WIPE_LO, O9_WIPE_HI, O10_ACC, O11_HORN, O12_IGN,
  O13_LS_ECU, O14_LS_FAN, O15_COMFORT, O16_BLOWER,
  O17_TURN_L, O18_TURN_R, O19_REVERSE, O20_INTERIOR,
  O21_START, O22_KEEPALIVE, O23_SPARE, O24_SPARE
};

/* How many channel currents are still guesses. Printed at boot so the
 * number in front of you is never mistaken for measured data. */
inline int estimatedChannelCount() {
    int n = 0;
    for (int i = 0; i < 24; i++) if (CH[i].src == EST) n++;
    return n;
}

#endif /* CHANNELS_H */
