#!/usr/bin/env python3
"""gen_vectors.py - the CAN map's test vectors, generated from the record (Y8, R2).

Reads 02-PROJECTS/01-electrical/data/can_messages.csv and can_fields.csv (the one bus map,
D-374) and writes can_vectors.h beside this script: one V_ID_* / V_TMO_* / V_RATE_* per
message and one V_<MACRO> bit number per named bit of every bitfield. test_vectors.cpp
includes it next to ../icu/can_map.h and static_asserts that every macro in the firmware
agrees - so a frame id, a timeout or a bit position that moves in the record fails the
suite until can_map.h follows it. The record is the master; this file is build output.

A bit the record names that this script cannot map to a firmware macro is an error (exit 1):
the firmware does not know that field yet, and run.sh must say so rather than pass.
Stdlib only, Python 3.9.
"""
import csv
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE.parents[2] / "data"
OUT = HERE / "can_vectors.h"

# message id -> the macro suffix can_map.h uses (ID_<suffix>, TMO_<suffix>)
MSG = {
    "0x100": "PMU_STATE", "0x110": "PMU_POWER", "0x120": "PMU_OUTPUTS", "0x130": "PMU_CHANNEL",
    "0x200": "ICU_SENSORS", "0x210": "ICU_HEALTH", "0x218": "ICU_BODY", "0x220": "ICU_BATT",
    "0x221": "ICU_CELLS", "0x222": "ICU_BATT_EXT", "0x300": "DCU_CLIMATE", "0x310": "DCU_COMFORT",
    "0x320": "DCU_RADAR", "0x400": "PANEL_KEYS",
}

# (message, byte) -> {record token (lower-cased, as can_fields writes it): firmware macro}.
# The bit number comes from the record; only the name needs this table. A byte listed here
# whose encoding names a token missing from its table is an error.
BITS = {
    ("0x100", "1"): {"acc": "WAKE_ACC", "run": "WAKE_RUN", "door": "WAKE_DOOR",
                     "horn / hazard / wink": "WAKE_A8", "self-hold o22": "WAKE_SELF",
                     "brake": "WAKE_BRAKE", "dcu request": "WAKE_DCU", "reserved": None},
    ("0x100", "2"): {"soft-fuse trip": "FAULT_SOFTFUSE", "undervolt": "FAULT_UNDERVOLT",
                     "overvolt": "FAULT_OVERVOLT", "overtemp": "FAULT_OVERTEMP"},
    ("0x100", "6"): {"a1": "INFAULT_A1", "a2": "INFAULT_A2", "a3": "INFAULT_A3", "a4": "INFAULT_A4",
                     "a5": "INFAULT_A5", "a6": "INFAULT_A6", "a8": "INFAULT_A8", "a15": "INFAULT_A15"},
    ("0x210", "0"): {"rpm": "SENS_RPM", "water": "SENS_WATER", "oil temp": "SENS_OILTEMP",
                     "oil press": "SENS_OILPRESS", "vss": "SENS_VSS", "fuel": "SENS_FUEL"},
    ("0x210", "1"): {"open": "SFAULT_OPEN", "short": "SFAULT_SHORT", "out of range": "SFAULT_RANGE",
                     "implausible": "SFAULT_IMPLAUSIBLE"},
    ("0x210", "2"): {"pmu seen": "CANH_PMU", "dcu seen": "CANH_DCU", "reserved": None, "afr seen": "CANH_AFR"},
    ("0x210", "3"): {"charge lamp": "TT_CHARGE", "brake warning": "TT_BRAKE", "turn l": "TT_TURN_L",
                     "turn r": "TT_TURN_R", "high beam": "TT_HIGH_BEAM", "reserved": None},
    ("0x220", "6"): {"advertisement fresh": "BATT_ADV_FRESH", "gatt connected": "BATT_GATT_CONN",
                     "cell frame fresh": "BATT_CELLS_FRESH", "checksum failed": "BATT_CSUM_FAILED",
                     "radio link lost": "BATT_RADIO_LOST"},
    ("0x320", "1"): {"x": "BAND_X", "k": "BAND_K", "ka": "BAND_KA", "laser": "BAND_LASER"},
    ("0x400", "0"): {"defog": "PK_DEFOG", "hatch release": "PK_HATCH", "fuel-door release": "PK_FUEL_DOOR",
                     "hvac mode": "PK_HVAC_MODE", "recirculate": "PK_RECIRC", "window drv up": "PK_WIN_DRV_UP",
                     "window drv down": "PK_WIN_DRV_DN", "window pass up": "PK_WIN_PASS_UP"},
    ("0x400", "1"): {"window pass down": "PK_WIN_PASS_DN", "mirror thumbstick press": "PK_MIRROR_PRESS",
                     "reserved": None},
}
BYTE_OFFSET = {("0x400", "1"): 8}   # byte 1 of the keys continues byte 0's 16-bit field

TOKEN = re.compile(r"\b(?:b|bit )(\d+)(?:-\d+)?\s+([^·]+?)(?=\s*·|\s*$|\s*\()")


def read(name):
    with open(DATA / name, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main() -> int:
    lines = ["/* can_vectors.h - generated by gen_vectors.py from can_messages.csv and can_fields.csv",
             " * (the record is the master, D-374). Do not edit; run.sh rewrites it. */",
             "#ifndef CAN_VECTORS_H", "#define CAN_VECTORS_H", ""]
    errors = []
    for m in read("can_messages.csv"):
        mid = (m.get("id") or "").strip()
        if mid not in MSG:
            continue
        suf = MSG[mid]
        lines.append(f"#define V_ID_{suf:<14} {mid}")
        rate = (m.get("rate_hz") or "").strip()
        if rate.isdigit():
            lines.append(f"#define V_RATE_{suf:<12} {rate}")
        tmo = (m.get("timeout_ms") or "").strip()
        if tmo.isdigit():
            lines.append(f"#define V_TMO_{suf:<13} {tmo}")
    lines.append("")
    for f in read("can_fields.csv"):
        key = ((f.get("msg") or "").strip(), (f.get("bytes") or "").strip())
        if key not in BITS:
            continue
        table = BITS[key]
        enc = (f.get("encoding") or "").replace("bitfield,", "").replace("bitfield:", "")
        seen = 0
        for num, name in TOKEN.findall(enc):
            tok = name.strip().lower()
            tok = re.split(r"\s+-\s+|\s*\(", tok)[0].strip()
            if tok not in table:
                errors.append(f"{key[0]} byte {key[1]}: no firmware macro for '{name.strip()}' - add it to can_map.h and gen_vectors.py")
                continue
            macro = table[tok]
            seen += 1
            if macro:
                lines.append(f"#define V_{macro:<18} {int(num) + BYTE_OFFSET.get(key, 0)}")
        if seen == 0:
            errors.append(f"{key[0]} byte {key[1]}: no bits parsed from '{enc.strip()[:60]}'")
    lines += ["", "#endif", ""]
    if errors:
        for e in errors:
            print("gen_vectors:", e)
        return 1
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen_vectors: {OUT.name} written, {sum(1 for l in lines if l.startswith('#define'))} vectors")
    return 0


if __name__ == "__main__":
    sys.exit(main())
