/*
 * test_dcu.cpp — desktop verification of the DCU logic (F-001)
 *
 * Compiles the REAL climate.h + panel.h + can_map.h from ../dcu. Covers the
 * seat interlock (D-073), comfort gating, keypad edges, servo mapping, the
 * SD climate-memory CRC, and F-017: the key matrix, 0x400, wake and replay,
 * the release select (D-370) and its interlock - stopped only, 1.5 s at most
 * (D-465) - knobs, windows (D-363), mirrors (D-359,
 * D-360), one servo at a time (D-379), the NTCs, current and mirror heat;
 * and D-452: the pin map (pins.h), the TCA9539-Q1 expander's ports, its
 * reset as the DRV8962's fault clear, and CAN STB held low (tca9539.h); and Y8:
 * the logic rows' terms the DCU supplies over 0x400, from logic_vectors.h.
 *
 * Build (g++ on PATH):
 *   g++ test_dcu.cpp -o test_dcu -std=c++17 -O2 -I../dcu && ./test_dcu
 */
#include <cstdio>
#include <cstring>
#include <vector>
#include "climate.h"
#include "panel.h"
#include "pins.h"
#include "tca9539.h"
#include "logic_vectors.h"   /* generated by gen_logic_vectors.py (run.sh) */

/* ---------- a TCA9539 on a mocked bus (tca9539.h's four calls) ----------
 * The model keeps the registers as the datasheet does - reset makes every
 * port an input and the output registers 0xFF; a write's data bytes
 * alternate within the register pair - and after every transaction it
 * records what each PIN is: an output port drives its register bit, an
 * input port floats to what is on it - nSLEEP (R35) and STB (R8) pulled
 * down, the DRV8962's IN / EN and the PROFETs' DEN / DSEL on their internal
 * pull-downs; nFAULT (R36), power-good (R3) and P17 (R58) pulled up. */
struct ExpModel {
    uint16_t out = 0xFFFF, pol = 0, cfg = 0xFFFF, in = 0xFFFF;
    bool nack = false, in_reset = false;
    int resets = 0, reads = 0;
    std::vector<uint8_t> regs_written;           /* the register byte of each write */
    std::vector<uint16_t> pins;                  /* pin levels after each transaction */
};
static ExpModel g_exp;
static uint16_t exp_pin_levels() {
    const uint16_t pulled_down = EXP_OUTPUTS;
    uint16_t floating = (uint16_t)(g_exp.in_reset ? 0xFFFF : g_exp.cfg);
    uint16_t driven = (uint16_t)(g_exp.out & ~floating);
    return (uint16_t)(driven | (floating & ~pulled_down));
}
uint8_t exp_hal_write(uint8_t addr, const uint8_t *buf, uint8_t n) {
    if (g_exp.nack || g_exp.in_reset || addr != TCA9539_ADDR || n < 1) return 0;
    uint8_t reg = buf[0];
    g_exp.regs_written.push_back(reg);
    for (uint8_t i = 1; i < n; i++) {
        uint8_t r = (uint8_t)((reg & 0xFE) | ((reg + i - 1) & 1));
        uint16_t *pair = r >= 6 ? &g_exp.cfg : r >= 4 ? &g_exp.pol : r >= 2 ? &g_exp.out : nullptr;
        if (!pair) continue;                     /* the input registers ignore writes */
        if (r & 1) *pair = (uint16_t)((*pair & 0x00FF) | (buf[i] << 8));
        else       *pair = (uint16_t)((*pair & 0xFF00) | buf[i]);
    }
    g_exp.pins.push_back(exp_pin_levels());
    return 1;
}
uint8_t exp_hal_read(uint8_t addr, uint8_t reg, uint8_t *buf, uint8_t n) {
    if (g_exp.nack || g_exp.in_reset || addr != TCA9539_ADDR || reg != TCA_REG_INPUT0 || n != 2) return 0;
    g_exp.reads++;
    buf[0] = (uint8_t)(g_exp.in & 0xFF); buf[1] = (uint8_t)(g_exp.in >> 8);
    return 1;
}
void exp_hal_reset(uint8_t asserted) {
    g_exp.in_reset = asserted != 0;
    if (asserted) { g_exp.resets++; g_exp.out = 0xFFFF; g_exp.pol = 0; g_exp.cfg = 0xFFFF; }
    g_exp.pins.push_back(exp_pin_levels());
}
void exp_hal_delay_us(uint32_t) {}
static void exp_model_fresh() { g_exp = ExpModel(); }

static int g_pass = 0, g_fail = 0;
#define CHECK(cond, msg) do { \
    if (cond) g_pass++; \
    else { g_fail++; printf("  FAIL %s:%d  %s\n", __FILE__, __LINE__, msg); } \
} while (0)

static dcu_state_t fresh() {
    dcu_state_t s;
    memset(&s, 0, sizeof s);
    mem_defaults(&s.mem);
    return s;
}

int main() {
    printf("-- DCU logic verification --\n");

    /* ============ 1. seat interlock (D-073) — heat wins ============ */
    {
        dcu_state_t s = fresh();
        s.mem.seat_heat = 0x02;            /* driver heat level 2   */
        s.mem.seat_cool = 0x01;            /* driver cool level 1   */
        enforce_seat_interlock(&s);
        CHECK(s.mem.seat_cool == 0, "driver cool cleared when driver heat on");
        CHECK(s.comfort_on[CMF_SEAT_HEAT_DRV] == 1 && s.comfort_on[CMF_SEAT_COOL_DRV] == 0,
              "driver channels: heat on, cool off");

        s = fresh();
        s.mem.seat_heat = 0x08;            /* passenger heat        */
        s.mem.seat_cool = 0x04 | 0x01;     /* passenger + driver cool */
        enforce_seat_interlock(&s);
        CHECK(s.mem.seat_cool == 0x01, "passenger cool cleared, driver cool untouched");
        CHECK(s.comfort_on[CMF_SEAT_COOL_DRV] == 1 && s.comfort_on[CMF_SEAT_COOL_PASS] == 0
              && s.comfort_on[CMF_SEAT_HEAT_PASS] == 1,
              "flags follow per-seat, not global");

        /* exhaustive: no (heat,cool) input ever leaves both on for a seat */
        bool never = true;
        for (int h = 0; h < 16 && never; h++)
            for (int c = 0; c < 16 && never; c++) {
                s = fresh();
                s.mem.seat_heat = (uint8_t)h; s.mem.seat_cool = (uint8_t)c;
                enforce_seat_interlock(&s);
                if ((s.mem.seat_heat & 3) && (s.mem.seat_cool & 3)) never = false;
                if ((s.mem.seat_heat & 0x0C) && (s.mem.seat_cool & 0x0C)) never = false;
            }
        CHECK(never, "all 256 heat/cool combos: never both on one seat");
    }

    /* ================= 1b. blower duty (D-308, F-012) ================= */
    {
        CHECK(blower_duty_pct(0) == 0,   "blower level 0 is 0 % - off is off");
        CHECK(blower_duty_pct(1) == 33 && blower_duty_pct(2) == 67, "levels 1-2 are 33 / 67 %");
        CHECK(blower_duty_pct(3) == 100, "level 3 is 100 %");
        CHECK(blower_duty_pct(9) == 100, "an out-of-range level clamps to 100 %, never wraps");
        CHECK(CMF_COUNT == 5, "five comfort channels - nozzles and de-icer cancelled (D-329)");
    }

    /* ================= 2. comfort gating ================= */
    {
        dcu_state_t s = fresh();
        s.key_pos = KEY_RUN; s.pmu_alive = 1;
        CHECK(comfort_permitted(&s) == 1, "RUN + PMU alive permits comfort");
        s.pmu_alive = 0;
        CHECK(comfort_permitted(&s) == 0, "dead PMU blocks comfort");
        s.pmu_alive = 1; s.key_pos = KEY_ACC;
        CHECK(comfort_permitted(&s) == 0, "ACC blocks comfort");
        s.key_pos = KEY_START;
        CHECK(comfort_permitted(&s) == 0, "cranking blocks comfort");
    }

    /* ================= 3. keypad edges ================= */
    {
        dcu_state_t s = fresh();               /* defaults: VENT, 21 C */
        apply_keypad(&s, KP_MODE);
        CHECK(s.mem.mode == CLIM_HEAT, "VENT -> HEAT");
        apply_keypad(&s, KP_MODE);
        CHECK(s.mem.mode == CLIM_DEFROST, "HEAT -> DEFROST");
        apply_keypad(&s, KP_MODE);
        CHECK(s.mem.mode == CLIM_VENT, "DEFROST wraps to VENT");
        s.mem.mode = CLIM_AC;                  /* out-of-cycle (corrupt/AC) */
        apply_keypad(&s, KP_MODE);
        CHECK(s.mem.mode == CLIM_VENT, "out-of-cycle mode lands on VENT");
        s.mem.mode = CLIM_OFF;
        apply_keypad(&s, KP_MODE);
        CHECK(s.mem.mode == CLIM_VENT, "OFF lands on VENT");

        s = fresh();
        for (int i = 0; i < 20; i++) apply_keypad(&s, KP_TEMP_UP);
        CHECK(s.mem.target_c == 30, "temp clamps at 30");
        for (int i = 0; i < 40; i++) apply_keypad(&s, KP_TEMP_DN);
        CHECK(s.mem.target_c == 16, "temp clamps at 16");

        uint8_t r0 = s.mem.recirc;
        apply_keypad(&s, KP_RECIRC);
        CHECK(s.mem.recirc == (r0 ^ 1), "recirc toggles");
        apply_keypad(&s, KP_RECIRC);
        CHECK(s.mem.recirc == r0, "recirc toggles back");
    }

    /* ================= 4. servo mapping ================= */
    {
        dcu_state_t s = fresh();               /* cal 1000..2000 us */
        s.mem.mode = CLIM_VENT;    mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_MODE].us_now == 1000, "VENT -> mode door min");
        s.mem.mode = CLIM_HEAT;    mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_MODE].us_now == 1500, "HEAT -> mode door mid");
        s.mem.mode = CLIM_DEFROST; mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_MODE].us_now == 2000, "DEFROST -> mode door max");
        uint16_t held = s.mem.cal[SRV_MODE].us_now;
        s.mem.mode = CLIM_OFF;     mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_MODE].us_now == held, "OFF leaves the door in place");

        s.mem.target_c = 16; mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_BLEND].us_now == 1000, "16 C -> blend min");
        s.mem.target_c = 30; mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_BLEND].us_now == 2000, "30 C -> blend max");
        s.mem.target_c = 23; mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_BLEND].us_now == 1500, "23 C -> blend mid");
        s.mem.target_c = 99; mode_to_servos(&s);   /* corrupt value */
        CHECK(s.mem.cal[SRV_BLEND].us_now == 2000, "target clamps before mapping");

        /* commanded pulse can never leave the calibrated window */
        bool inWin = true;
        for (int m = 0; m <= CLIM_AC; m++)
            for (int t = 0; t < 256; t++) {
                s.mem.mode = (uint8_t)m; s.mem.target_c = (uint8_t)t;
                s.mem.recirc = (uint8_t)(t & 1);
                mode_to_servos(&s);
                for (int v = 0; v < SRV_COUNT; v++)
                    if (s.mem.cal[v].us_now < 1000 || s.mem.cal[v].us_now > 2000) inWin = false;
            }
        CHECK(inWin, "all modes x all targets: pulses stay in 1000..2000");

        s.mem.recirc = 1; mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_RECIRC].us_now == 2000, "recirc -> door max");
        s.mem.recirc = 0; mode_to_servos(&s);
        CHECK(s.mem.cal[SRV_RECIRC].us_now == 1000, "fresh -> door min");
    }

    /* ================= 5. climate-memory CRC ================= */
    {
        climate_mem_t m; mem_defaults(&m);
        m.crc = mem_crc(&m);
        CHECK(m.crc == mem_crc(&m), "crc field itself is excluded from the sum");

        climate_mem_t bad = m;
        bad.target_c ^= 0x40;                  /* one flipped bit */
        CHECK(mem_crc(&bad) != m.crc, "single-bit corruption changes the CRC");

        uint8_t blob[sizeof(climate_mem_t)];   /* SD round-trip */
        memcpy(blob, &m, sizeof m);
        climate_mem_t back; memcpy(&back, blob, sizeof back);
        CHECK(back.crc == mem_crc(&back), "byte round-trip keeps a valid CRC");

        CHECK(m.mode == CLIM_VENT && m.target_c == 21, "defaults: VENT, 21 C");
    }

    /* ================= 6. key matrix and debounce (D-380, F-016) ================= */
    {
        CHECK(matrix_bit(0, 0) == PK_DEFOG && matrix_bit(0, 1) == PK_HATCH && matrix_bit(0, 2) == PK_FUEL_DOOR,
              "ROW1: defog, hatch, fuel door");
        CHECK(matrix_bit(1, 0) == PK_HVAC_MODE && matrix_bit(1, 1) == PK_RECIRC && matrix_bit(1, 2) == PK_WIN_DRV_UP,
              "ROW2: mode, recirc, DRV up");
        CHECK(matrix_bit(2, 0) == PK_WIN_DRV_DN && matrix_bit(2, 1) == PK_WIN_PASS_UP && matrix_bit(2, 2) == PK_WIN_PASS_DN,
              "ROW3: DRV down, PASS up, PASS down");

        panel_t p; memset(&p, 0, sizeof p);
        uint16_t e = 0;
        for (int i = 0; i < KEY_DEBOUNCE_SCANS - 1; i++) e |= keys_debounce(&p, PK_RECIRC);
        CHECK(e == 0 && p.phys == 0, "a key is not down before the debounce");
        e = keys_debounce(&p, PK_RECIRC);
        CHECK(e == PK_RECIRC && p.phys == PK_RECIRC, "down after the debounce, one edge");
        CHECK(keys_debounce(&p, 0) == 0 && p.phys == PK_RECIRC, "one bounce open does not release it");
        e = 0;
        for (int i = 0; i < 20; i++) e |= keys_debounce(&p, (i & 1) ? PK_RECIRC : 0);
        CHECK(e == 0, "chatter makes no second edge");
    }

    /* ================= 7. 0x400: held, heartbeat, wake and replay (D-355) ================= */
    {
        panel_t p; memset(&p, 0, sizeof p);
        uint16_t down = 0, held = 0; uint32_t t = 10000;
        for (int i = 0; i < 10; i++, t += 5) panel_keys_step(&p, PK_WIN_DRV_UP, 1, t, &down, &held);
        CHECK(down == PK_WIN_DRV_UP && held == 0, "window key down, not yet held");
        for (int i = 0; i < 200; i++, t += 5) panel_keys_step(&p, PK_WIN_DRV_UP, 1, t, &down, &held);
        CHECK(held == PK_WIN_DRV_UP, "held after 1 s");

        keys_tx_t tx; memset(&tx, 0, sizeof tx); panel_keys_t f;
        CHECK(panel_frame_due(&tx, 1, 0, 0, &f) == 1 && f.down == 1 && f.counter == 0, "first frame goes");
        CHECK(panel_frame_due(&tx, 1, 0, 100, &f) == 0, "no change, no frame");
        CHECK(panel_frame_due(&tx, 3, 0, 150, &f) == 1 && f.counter == 1, "a change goes at once");
        CHECK(panel_frame_due(&tx, 3, 0, 649, &f) == 0 && panel_frame_due(&tx, 3, 0, 650, &f) == 1,
              "2 Hz heartbeat");
        CHECK(sizeof(panel_keys_t) == CAN_MSG_LEN, "0x400 payload is 8 bytes");

        /* asleep: a defog tap wakes the PMU and is replayed once it answers */
        memset(&p, 0, sizeof p); t = 20000;
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, PK_DEFOG, 0, t, &down, &held);
        CHECK(p.wake_req == 1 && down == 0, "asleep: wake pulled, the edge key held back");
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, 0, 0, t, &down, &held);
        CHECK(p.wake_req == 1 && p.latched == PK_DEFOG, "released before the PMU woke: latched");
        panel_keys_step(&p, 0, 1, t, &down, &held); t += 5;
        CHECK(p.wake_req == 0 && down == PK_DEFOG, "PMU alive: the tap is replayed");
        for (int i = 0; i < REPLAY_MS / 5 + 1; i++, t += 5) panel_keys_step(&p, 0, 1, t, &down, &held);
        CHECK(down == 0, "and released after the replay");

        /* a PMU that never answers drops the latched press */
        memset(&p, 0, sizeof p); t = 30000;
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, PK_HATCH, 0, t, &down, &held);
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, 0, 0, t, &down, &held);
        t += WAKE_REQ_MAX_MS;
        panel_keys_step(&p, 0, 0, t, &down, &held);
        CHECK(p.wake_req == 0 && p.latched == 0, "no answer in 3 s: wake and the press dropped");
        panel_keys_step(&p, 0, 1, t + 5, &down, &held);
        CHECK(down == 0 && p.rel_sel == 0, "a late PMU never pops the hatch");

        /* a CAN hiccup with defog held makes no second edge */
        memset(&p, 0, sizeof p); t = 40000;
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, PK_DEFOG, 1, t, &down, &held);
        panel_keys_step(&p, PK_DEFOG, 0, t, &down, &held); t += 5;
        CHECK(down == PK_DEFOG, "PMU lost with the key held: it stays down, no new edge later");

        CHECK(sleep_due(&p, 0, DCU_SLEEP_AFTER_MS) == 0, "no sleep with a key down");
        panel_t q; memset(&q, 0, sizeof q);
        CHECK(sleep_due(&q, 0, DCU_SLEEP_AFTER_MS) == 1 && sleep_due(&q, 1, DCU_SLEEP_AFTER_MS) == 0
              && sleep_due(&q, 0, DCU_SLEEP_AFTER_MS - 1) == 0, "sleep: PMU gone, idle 30 s");
    }

    /* ================= 8. release select (D-370, D-465) ================= */
    {
        panel_t p; memset(&p, 0, sizeof p); p.stopped = 1;
        uint16_t down = 0, held = 0; uint32_t t = 50000;
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        CHECK(p.rel_sel == PK_HATCH && down == PK_HATCH, "hatch: K3 selected in the same scan the edge goes");
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, PK_HATCH | PK_FUEL_DOOR, 1, t, &down, &held);
        CHECK(p.rel_sel == PK_HATCH && !(down & PK_FUEL_DOOR), "fuel door during the hatch hold: refused, kept off 0x400");
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, 0, 1, t, &down, &held);
        CHECK(p.rel_sel == PK_HATCH, "held through the pulse after the key is let go");
        t += RELEASE_HOLD_MS;
        panel_keys_step(&p, 0, 1, t, &down, &held);
        CHECK(p.rel_sel == 0, "released after the hold");

        memset(&p, 0, sizeof p); p.stopped = 1;
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, PK_HATCH | PK_FUEL_DOOR, 1, t, &down, &held);
        CHECK(p.rel_sel == 0 && !(down & PK_RELEASE), "both at once: neither, and the PMU sees neither");

        /* D-465: the select is dropped 1.5 s after it was raised, whatever the key does */
        memset(&p, 0, sizeof p); p.stopped = 1; t = 60000;
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, PK_FUEL_DOOR, 1, t, &down, &held);
        uint32_t t0 = p.rel_t0;
        CHECK(p.rel_sel == PK_FUEL_DOOR && (down & PK_FUEL_DOOR), "fuel door: K4 selected, the edge goes");
        while ((uint32_t)(t + 5 - t0) < RELEASE_HOLD_MS) { t += 5; panel_keys_step(&p, PK_FUEL_DOOR, 1, t, &down, &held); }
        CHECK(p.rel_sel == PK_FUEL_DOOR, "key held: still selected 5 ms before 1.5 s");
        t += 5; panel_keys_step(&p, PK_FUEL_DOOR, 1, t, &down, &held);
        CHECK(p.rel_sel == 0, "key still held: the select drops at 1.5 s (D-465)");
        for (int i = 0; i < 2000; i++) { t += 5; panel_keys_step(&p, PK_FUEL_DOOR, 1, t, &down, &held); }
        CHECK(p.rel_sel == 0 && (down & PK_FUEL_DOOR), "held 10 s more: never re-selected; 0x400 shows the key, no new edge");
        for (int i = 0; i < 6; i++) { t += 5; panel_keys_step(&p, 0, 1, t, &down, &held); }
        for (int i = 0; i < 4; i++) { t += 5; panel_keys_step(&p, PK_FUEL_DOOR, 1, t, &down, &held); }
        CHECK(p.rel_sel == PK_FUEL_DOOR, "let go and pressed again: a new select");

        /* a second press of the same key inside the window never extends it */
        memset(&p, 0, sizeof p); p.stopped = 1; t = 70000;
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        t0 = p.rel_t0;
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, 0, 1, t, &down, &held);
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        CHECK(p.rel_t0 == t0 && !(down & PK_HATCH), "hatch pressed again inside 1.5 s: refused, kept off 0x400, window unchanged");
        while ((uint32_t)(t - t0) < RELEASE_HOLD_MS) { panel_keys_step(&p, PK_HATCH, 1, t, &down, &held); t += 5; }
        panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        CHECK(p.rel_sel == 0, "and the select still drops 1.5 s after the first press");

        /* D-465: refused unless the car is stopped - 0x200's road speed at 0, fresh */
        CHECK(car_stopped(1, 0, 0) == 1 && car_stopped(1, TMO_ICU_SENSORS, 0) == 1, "0x200 fresh, 0 km/h: stopped");
        CHECK(car_stopped(1, 0, 1) == 0 && car_stopped(1, 0, 120) == 0, "1 km/h or more: moving");
        CHECK(car_stopped(1, TMO_ICU_SENSORS + 1, 0) == 0, "0x200 stale (older than TMO_ICU_SENSORS): NOT stopped");
        CHECK(car_stopped(0, 0, 0) == 0, "no 0x200 since boot: NOT stopped");

        memset(&p, 0, sizeof p); t = 80000;
        CHECK(p.stopped == 0, "a fresh panel_t refuses: stopped resets to 0");
        p.stopped = car_stopped(1, 0, 30);                                  /* moving */
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        CHECK(p.rel_sel == 0 && !(down & PK_HATCH), "moving: hatch refused - no select, nothing on 0x400");
        p.stopped = car_stopped(1, 0, 0);
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        CHECK(p.rel_sel == 0 && !(down & PK_HATCH), "stopped while the refused key is held: still refused until let go");
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, 0, 1, t, &down, &held);
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        CHECK(p.rel_sel == PK_HATCH && (down & PK_HATCH), "let go, pressed stopped: K3 selected, the edge goes");

        memset(&p, 0, sizeof p); t = 90000;
        p.stopped = car_stopped(1, TMO_ICU_SENSORS + 50, 0);                /* stale */
        for (int i = 0; i < 6; i++, t += 5) panel_keys_step(&p, PK_FUEL_DOOR, 1, t, &down, &held);
        CHECK(p.rel_sel == 0 && !(down & PK_FUEL_DOOR), "0x200 stale: fuel door refused");

        memset(&p, 0, sizeof p); p.stopped = 1; t = 95000;
        for (int i = 0; i < 4; i++, t += 5) panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        CHECK(p.rel_sel == PK_HATCH, "stopped: K3 selected");
        p.stopped = 0;                                                      /* the car moves off, or 0x200 goes stale */
        t += 5; panel_keys_step(&p, PK_HATCH, 1, t, &down, &held);
        CHECK(p.rel_sel == 0 && !(down & PK_HATCH), "not stopped mid-select: dropped at once, the key kept off 0x400");

        /* exhaustive: over random key, PMU and speed sequences the select is never both,
         * never raised or kept while not stopped, never older than 1.5 s, and a release
         * edge reaches 0x400 only with its own relay selected */
        bool ok = true; uint32_t seed = 12345;
        memset(&p, 0, sizeof p);
        uint16_t prev_down = 0;
        for (int i = 0; i < 200000 && ok; i++, t += 5) {
            seed = seed * 1103515245u + 12345u;
            uint16_t raw = (uint16_t)((seed >> 16) & PK_RELEASE);
            uint8_t alive = ((seed >> 8) & 31) != 0;
            p.stopped = ((seed >> 3) & 15) != 0;
            panel_keys_step(&p, raw, alive, t, &down, &held);
            if (p.rel_sel != 0 && p.rel_sel != PK_HATCH && p.rel_sel != PK_FUEL_DOOR) ok = false;
            if (p.rel_sel && (!p.stopped || (uint32_t)(t - p.rel_t0) >= RELEASE_HOLD_MS)) ok = false;
            uint16_t edge = (uint16_t)(down & ~prev_down & PK_RELEASE);
            if (edge && edge != p.rel_sel) ok = false;
            prev_down = down;
        }
        CHECK(ok, "200k random scans: one relay at most, only stopped, never past 1.5 s, every release edge steered");
    }

    /* ================= 9. encoders and knobs (SN20, D-073) ================= */
    {
        enc_t e; memset(&e, 0, sizeof e); e.ab = 3;
        const uint8_t cw[4] = { 2, 0, 1, 3 };           /* 11 -> 10 -> 00 -> 01 -> 11 */
        int d = 0;
        for (int k = 0; k < 4; k++) d += enc_step(&e, cw[k]);
        CHECK(d == 1, "one clockwise detent");
        for (int k = 3; k >= 0; k--) d += enc_step(&e, k ? cw[k - 1] : 3);
        CHECK(d == 0, "one anticlockwise detent back");
        d = 0;
        for (int k = 0; k < 50; k++) { d += enc_step(&e, 2); d += enc_step(&e, 3); }
        CHECK(d == 0, "contact bounce on one edge adds nothing");

        dcu_state_t s = fresh();
        panel_apply(&s, 0, 0, 0, 2, 0);
        CHECK((s.mem.seat_heat & 3) == 2 && (s.mem.seat_cool & 3) == 0, "driver knob +2: heat 2");
        panel_apply(&s, 0, 0, 0, -4, 0);
        CHECK((s.mem.seat_heat & 3) == 0 && (s.mem.seat_cool & 3) == 2, "then -4: through OFF to cool 2");
        panel_apply(&s, 0, 0, 0, -9, 5);
        CHECK((s.mem.seat_cool & 3) == 3 && ((s.mem.seat_heat >> 2) & 3) == 3, "clamped at cool 3 / heat 3");
        bool never = true;
        for (int a = -8; a <= 8; a++) for (int b = -8; b <= 8; b++) {
            panel_apply(&s, 0, 0, 0, a, b);
            if ((s.mem.seat_heat & 3) && (s.mem.seat_cool & 3)) never = false;
            if ((s.mem.seat_heat & 0xC) && (s.mem.seat_cool & 0xC)) never = false;
        }
        CHECK(never, "no knob sequence heats and cools one seat");

        s = fresh();
        panel_apply(&s, 0, 5, 0, 0, 0);
        CHECK(s.mem.blower == 3, "fan clamps at 3");
        panel_apply(&s, 0, -9, 0, 0, 0);
        CHECK(s.mem.blower == 0, "fan clamps at off");
        panel_apply(&s, 0, 0, 3, 0, 0);
        CHECK(s.mem.target_c == 24, "temperature knob: one degree a detent");
        panel_apply(&s, PK_HVAC_MODE | PK_RECIRC, 0, 0, 0, 0);
        CHECK(s.mem.mode == CLIM_HEAT && s.mem.recirc == 1, "mode and recirc keys");
        panel_apply(&s, PK_DEFOG | PK_HATCH, 0, 0, 0, 0);
        CHECK(s.mem.mode == CLIM_HEAT, "PMU keys do nothing locally");
    }

    /* ================= 10. windows (SN22, D-363) ================= */
    {
        window_t w; memset(&w, 0, sizeof w);
        uint8_t up, dn; uint32_t t = 60000;
        window_step(&w, 1, 0, 1, t, &up, &dn);
        CHECK(up == 1 && dn == 0, "up key: up relay");
        window_step(&w, 0, 1, 1, t += 5, &up, &dn);
        CHECK(up == 0 && dn == 0, "reversal: both at rest first");
        window_step(&w, 0, 1, 1, t += WINDOW_DEAD_MS - 10, &up, &dn);
        CHECK(dn == 0, "still resting inside the dead time");
        window_step(&w, 0, 1, 1, t += 10, &up, &dn);
        CHECK(dn == 1 && up == 0, "then down");
        window_step(&w, 1, 1, 1, t += 5, &up, &dn);
        CHECK(up == 0 && dn == 0, "both keys: stop");
        window_step(&w, 1, 0, 0, t += 500, &up, &dn);
        CHECK(up == 0, "not permitted: nothing");
        window_step(&w, 1, 0, 1, t += 5, &up, &dn);
        window_step(&w, 1, 0, 1, t += WINDOW_MAX_RUN_MS, &up, &dn);
        CHECK(up == 0, "held past the run limit: stops");
        window_step(&w, 1, 0, 1, t += 500, &up, &dn);
        CHECK(up == 0, "and stays stopped until let go");
        window_step(&w, 0, 0, 1, t += 5, &up, &dn);
        window_step(&w, 1, 0, 1, t += WINDOW_DEAD_MS, &up, &dn);
        CHECK(up == 1, "let go and pressed again: runs");

        bool never = true; uint32_t seed = 777;
        memset(&w, 0, sizeof w);
        for (int i = 0; i < 100000 && never; i++) {
            seed = seed * 1103515245u + 12345u;
            window_step(&w, (seed >> 16) & 1, (seed >> 17) & 1, ((seed >> 18) & 7) != 0,
                        t += (seed >> 20) & 63, &up, &dn);
            if (up && dn) never = false;
        }
        CHECK(never, "100k random steps: up and down never together");
    }

    /* ================= 11. mirrors (SN17, D-359, D-360) ================= */
    {
        stick_cal_t c; stick_defaults(&c);
        uint8_t axis; int8_t dir;
        stick_read(&c, 2048 + 300, 2048, &axis, &dir);
        CHECK(axis == AXIS_NONE, "inside the dead band: nothing");
        stick_read(&c, 4000, 2600, &axis, &dir);
        CHECK(axis == AXIS_X && dir == MIRROR_SIGN_X, "the larger deflection wins");
        stick_read(&c, 2048, 100, &axis, &dir);
        CHECK(axis == AXIS_Y && dir == -MIRROR_SIGN_Y, "Y the other way");

        mirror_t m; memset(&m, 0, sizeof m); mirror_out_t o; uint32_t t = 70000;
        mirror_step(&m, 0, AXIS_X, 1, 1, t, &o);
        CHECK(o.left == HB_HIGH && o.common == HB_LOW && o.right == HB_OFF, "left side by default, right open");
        CHECK(o.clutch == (AXIS_X == MIRROR_CLUTCH_AXIS), "clutch follows the axis");
        mirror_step(&m, 0, AXIS_X, -1, 1, t += 5, &o);
        CHECK(o.left == HB_OFF && o.common == HB_OFF, "reversal: bridges open first");
        mirror_step(&m, 0, AXIS_X, -1, 1, t += MIRROR_DEAD_MS, &o);
        CHECK(o.left == HB_LOW && o.common == HB_HIGH, "then reversed polarity");
        mirror_step(&m, PK_MIRROR_PRESS, AXIS_Y, 1, 1, t += 5, &o);
        CHECK(m.side == MIRROR_RIGHT && o.left == HB_OFF && o.right == HB_OFF, "press: side toggles, all stop");
        CHECK(o.clutch == (AXIS_Y == MIRROR_CLUTCH_AXIS), "clutch settles during the dead time");
        mirror_step(&m, 0, AXIS_Y, 1, 1, t += MIRROR_DEAD_MS, &o);
        CHECK(o.right == HB_HIGH && o.left == HB_OFF, "right mirror moves, left open");
        mirror_step(&m, 0, AXIS_Y, 1, 0, t += 5, &o);
        CHECK(o.right == HB_OFF && o.common == HB_OFF && o.clutch == 0, "not permitted: everything open");

        bool ok = true; uint32_t seed = 4242;
        memset(&m, 0, sizeof m);
        for (int i = 0; i < 100000 && ok; i++) {
            seed = seed * 1103515245u + 12345u;
            uint8_t ax = (uint8_t)((seed >> 16) % 3);
            int8_t  dr = ax ? (((seed >> 18) & 1) ? 1 : -1) : 0;
            mirror_step(&m, ((seed >> 19) & 15) == 0 ? PK_MIRROR_PRESS : 0, ax, dr,
                        ((seed >> 23) & 7) != 0, t += (seed >> 24) & 31, &o);
            if (o.left != HB_OFF && o.right != HB_OFF) ok = false;          /* one mirror at a time */
            if ((o.left != HB_OFF || o.right != HB_OFF) == (o.common == HB_OFF)) ok = false;
            if (o.common != HB_OFF && (o.left == o.common || o.right == o.common)) ok = false;
        }
        CHECK(ok, "100k random steps: one side driven, always against the common");
    }

    /* ================= 12. servos one at a time (D-379) ================= */
    {
        dcu_state_t s = fresh();
        mode_to_servos(&s);                    /* targets 1000 / 1357 / 1000 us */
        servo_seq_t q; memset(&q, 0, sizeof q);
        uint32_t t = 80000;
        CHECK(servo_seq_step(&q, s.mem.cal, t) >= 0, "first servo moves");
        CHECK(servo_seq_step(&q, s.mem.cal, t + SERVO_SETTLE_MS - 1) == -1, "the next waits for the settle");
        CHECK(servo_seq_step(&q, s.mem.cal, t + SERVO_SETTLE_MS) >= 0, "then moves");
        CHECK(servo_seq_step(&q, s.mem.cal, t + 2 * SERVO_SETTLE_MS) >= 0, "third");
        CHECK(servo_seq_step(&q, s.mem.cal, t + 3 * SERVO_SETTLE_MS) == -1, "nothing left to move");
        bool same = true;
        for (int i = 0; i < SRV_COUNT; i++) if (q.applied[i] != s.mem.cal[i].us_now) same = false;
        CHECK(same, "every servo reached its target");
    }

    /* ================= 13. analog inputs and mirror heat ================= */
    {
        CHECK(ntc_to_c(2048) == 25, "NTC at mid-scale reads 25 C");
        CHECK(ntc_to_c(0) == TEMP_INVALID && ntc_to_c(4095) == TEMP_INVALID, "short and open read blank");
        CHECK(ntc_to_c(1000) > 25 && ntc_to_c(3000) < 25, "hotter pulls the divider down");
        CHECK(comfort_current_ca(1241, 0) == 1000, "1.0 V at the ADC is 10.00 A");
        CHECK(comfort_current_ca(50, 60) == 0, "below the zero reads 0, never wraps");

        pmu_outputs_t m; memset(&m, 0, sizeof m);
        m.out_state[0] = 0x08;
        CHECK(pmu_out_on(&m, PMU_OUT_DEFOG) == 1 && pmu_out_on(&m, 0) == 0, "O4 is 0x120 byte 2 bit 3");
        m.out_state[2] = 0x80;
        CHECK(pmu_out_on(&m, 23) == 1, "O24 is byte 4 bit 7");
    }

    /* ================= 14. pin map (pins.h = dcu_channels.teensy_pin, D-452) ================= */
    {
        int uses[64] = { 0 };
        auto use = [&](int p) { if (p >= 0 && p < 64) uses[p]++; };
        use(PIN_CAN_RX); use(PIN_CAN_TX);
        for (int p : PIN_SERVO) use(p);
        for (int p : PIN_COMFORT) use(p);
        use(PIN_BLOWER); use(PIN_WAKE); use(PIN_EXP_INT); use(PIN_EXP_RESET);
        use(PIN_CABIN_NTC); use(PIN_OAT_NTC); use(PIN_CURRENT); use(PIN_JOY_PRESS);
        use(PIN_I2C_SDA); use(PIN_I2C_SCL); use(PIN_JOY_X); use(PIN_JOY_Y);
        for (int p : PIN_WIN) use(p);
        use(PIN_REL_HATCH); use(PIN_REL_FUEL);
        for (int p : PIN_ROW) use(p);
        for (int p : PIN_COL) use(p);
        for (int i = 0; i < ENC_COUNT; i++) { use(PIN_ENC_A[i]); use(PIN_ENC_B[i]); }
        bool once = true, pads = true;
        for (int p = 0; p <= 41; p++) if (uses[p] != 1) once = false;
        for (int p = 42; p < 64; p++) if (uses[p] != 0) pads = false;
        CHECK(once, "every edge pin 0-41 used exactly once (D-452: all 42)");
        CHECK(pads, "nothing on the bottom pads 48-54 (or any pad past 41)");

        CHECK(PIN_ENC_A[ENC_FAN] == 40 && PIN_ENC_B[ENC_FAN] == 41, "fan encoder on 40 / 41 (SN20, D-452)");
        CHECK(PIN_ENC_A[ENC_TEMP] == 34 && PIN_ENC_B[ENC_TEMP] == 35 && PIN_ENC_A[ENC_SEAT_DRV] == 36
              && PIN_ENC_B[ENC_SEAT_DRV] == 37 && PIN_ENC_A[ENC_SEAT_PASS] == 38 && PIN_ENC_B[ENC_SEAT_PASS] == 39,
              "temperature 34 / 35, driver seat 36 / 37, passenger seat 38 / 39");
        CHECK(PIN_I2C_SDA == 18 && PIN_I2C_SCL == 19 && PIN_EXP_INT == 12 && PIN_EXP_RESET == 13,
              "the expander on Wire 18 / 19, INT 12, RESET 13 (SN17)");
        bool no_enc_on_i2c = true;
        for (int i = 0; i < ENC_COUNT; i++)
            if (PIN_ENC_A[i] == 18 || PIN_ENC_A[i] == 19 || PIN_ENC_B[i] == 18 || PIN_ENC_B[i] == 19) no_enc_on_i2c = false;
        CHECK(no_enc_on_i2c, "no encoder left on the I2C pins");
        CHECK(PIN_ROW[0] == 28 && PIN_ROW[2] == 30 && PIN_COL[0] == 31 && PIN_COL[2] == 33, "matrix rows 28-30, columns 31-33 (SN19)");
        CHECK(PIN_JOY_X == 20 && PIN_JOY_Y == 21 && PIN_JOY_PRESS == 17, "thumbstick A6 / A7, press 17 (SN18)");
        CHECK(PIN_WIN[0] == 22 && PIN_WIN[1] == 23 && PIN_WIN[2] == 24 && PIN_WIN[3] == 25, "windows 22-25 (SN22)");
        CHECK(PIN_REL_HATCH == 26 && PIN_REL_FUEL == 27 && PIN_WAKE == 11 && PIN_BLOWER == 10,
              "release 26 / 27 (SN23), wake 11 (SN21), blower 10 (SN14)");
        CHECK(PIN_COMFORT[CMF_SEAT_HEAT_DRV] == 5 && PIN_COMFORT[CMF_SEAT_HEAT_PASS] == 6
              && PIN_COMFORT[CMF_SEAT_COOL_DRV] == 7 && PIN_COMFORT[CMF_SEAT_COOL_PASS] == 8
              && PIN_COMFORT[CMF_MIRROR_HEAT] == 9, "comfort 5-9 in climate.h's order (SN16)");
        CHECK(PIN_CABIN_NTC == 14 && PIN_OAT_NTC == 15 && PIN_CURRENT == 16 && PIN_SERVO[0] == 2 && PIN_SERVO[2] == 4,
              "NTCs A0 / A1, current A2, servos 2-4");
        CHECK(sizeof PIN_SERVO / sizeof PIN_SERVO[0] == SRV_COUNT && sizeof PIN_COMFORT / sizeof PIN_COMFORT[0] == CMF_COUNT,
              "one pin per servo and per comfort channel");
    }

    /* ================= 15. the expander's ports (TCA9539-Q1, SN17 / SN22 / SN16 / SN26 / SN24) ================= */
    {
        CHECK(TCA_REG_INPUT0 == 0x00 && TCA_REG_OUTPUT0 == 0x02 && TCA_REG_POLARITY0 == 0x04 && TCA_REG_CONFIG0 == 0x06,
              "register map: input 0/1, output 2/3, polarity 4/5, config 6/7");
        CHECK(TCA9539_ADDR == 0x74, "address 0x74: A0 = A1 = GND on the sheet (confirm)");
        CHECK(EXP_MIR_IN1 == 0x0001 && EXP_MIR_EN1 == 0x0002 && EXP_MIR_IN2 == 0x0004 && EXP_MIR_EN2 == 0x0008
              && EXP_MIR_IN3 == 0x0010 && EXP_MIR_EN3 == 0x0020, "P00-P05: IN1 / EN1 - IN3 / EN3");
        CHECK(EXP_MIR_EN4 == 0x0040 && EXP_MIR_NSLEEP == 0x0080 && EXP_MIR_NFAULT == 0x0100,
              "P06 EN4 (clutch), P07 nSLEEP, P10 nFAULT");
        CHECK(EXP_WIN_DEN == 0x0200 && EXP_WIN_DSEL0 == 0x0400 && EXP_WIN_DSEL1 == 0x0800 && EXP_MH_DEN == 0x1000,
              "P11-P13 window DEN / DSEL0 / DSEL1, P14 mirror-heat DEN");
        CHECK(EXP_CAN_STB == 0x2000 && EXP_PG_5V == 0x4000 && EXP_P17 == 0x8000, "P15 CAN STB, P16 power-good, P17");
        CHECK(EXP_INPUTS == 0xC100, "inputs: nFAULT, power-good, P17 - every other port drives");

        mirror_out_t mo; memset(&mo, 0, sizeof mo);
        CHECK(exp_word(&mo, 0, 0) == 0, "asleep: nothing but low");
        CHECK(exp_word(&mo, 1, 1) == EXP_MIR_NSLEEP, "awake, at rest: nSLEEP only, every bridge open");
        mo.common = HB_LOW; mo.left = HB_HIGH; mo.clutch = 1;
        CHECK(exp_word(&mo, 1, 1) == (EXP_MIR_NSLEEP | EXP_MIR_EN1 | EXP_MIR_IN2 | EXP_MIR_EN2 | EXP_MIR_EN4),
              "left up: common low, left high, clutch sinking");
        CHECK(exp_word(&mo, 1, 0) == EXP_MIR_NSLEEP, "not live (waking or faulted): every EN off");
        CHECK(exp_word(&mo, 0, 1) == 0, "asleep: no EN either");
        mo.common = HB_HIGH; mo.left = HB_OFF; mo.right = HB_LOW; mo.clutch = 0;
        CHECK(exp_word(&mo, 1, 1) == (EXP_MIR_NSLEEP | EXP_MIR_IN1 | EXP_MIR_EN1 | EXP_MIR_EN3),
              "right the other way: common high, right low, clutch open");

        CHECK(exp_open_first(EXP_MIR_EN1, EXP_MIR_EN1 | EXP_MIR_IN1) == 0, "a live bridge changing rail opens first");
        CHECK(exp_open_first(EXP_MIR_EN1, EXP_MIR_EN1 | EXP_MIR_EN2) == EXP_MIR_EN1, "a new channel needs no gap");

        /* the mirror step through the word: one head, against the common, STB never */
        bool ok = true; uint32_t seed = 9090, t = 90000;
        mirror_t m; memset(&m, 0, sizeof m);
        for (int i = 0; i < 100000 && ok; i++) {
            seed = seed * 1103515245u + 12345u;
            uint8_t ax = (uint8_t)((seed >> 16) % 3);
            int8_t  dr = ax ? (((seed >> 18) & 1) ? 1 : -1) : 0;
            mirror_step(&m, ((seed >> 19) & 15) == 0 ? PK_MIRROR_PRESS : 0, ax, dr,
                        ((seed >> 23) & 7) != 0, t += (seed >> 24) & 31, &mo);
            uint16_t w = exp_word(&mo, 1, 1);
            if ((w & EXP_MIR_EN2) && (w & EXP_MIR_EN3)) ok = false;                 /* one head */
            if (((w & (EXP_MIR_EN2 | EXP_MIR_EN3)) != 0) != ((w & EXP_MIR_EN1) != 0)) ok = false;
            if ((w & EXP_MIR_EN1) && (w & EXP_MIR_EN2) && !((w ^ (w >> 2)) & EXP_MIR_IN1)) ok = false;
            if ((w & EXP_MIR_EN1) && (w & EXP_MIR_EN3) && !((w ^ (w >> 4)) & EXP_MIR_IN1)) ok = false;
            if (w & (EXP_CAN_STB | EXP_INPUTS | EXP_WIN_DEN | EXP_WIN_DSEL0 | EXP_WIN_DSEL1 | EXP_MH_DEN)) ok = false;
        }
        CHECK(ok, "100k mirror steps: one head, always against the common, STB / DEN / inputs never driven");
    }

    /* ================= 16. reset: boot and the DRV8962's fault clear ================= */
    {
        exp_model_fresh();
        tca9539_t x; memset(&x, 0, sizeof x);
        CHECK(exp_reset_init(&x) == 1 && x.ok == 1 && g_exp.resets == 1, "boot: one reset pulse, acknowledged");
        CHECK(g_exp.regs_written.size() == 3 && g_exp.regs_written[0] == TCA_REG_OUTPUT0
              && g_exp.regs_written[1] == TCA_REG_POLARITY0 && g_exp.regs_written[2] == TCA_REG_CONFIG0,
              "outputs written low BEFORE the directions (they reset to 0xFF)");
        CHECK(g_exp.out == 0 && g_exp.cfg == EXP_INPUTS && g_exp.pol == 0 && g_exp.reads == 1,
              "after init: outputs low, three inputs, plain polarity, INT cleared by a read");
        bool quiet = true;
        for (uint16_t p : g_exp.pins)
            if (p & (EXP_MIR_NSLEEP | EXP_MIR_EN1 | EXP_MIR_EN2 | EXP_MIR_EN3 | EXP_MIR_EN4 | EXP_CAN_STB)) quiet = false;
        CHECK(quiet, "no EN, nSLEEP or STB pin goes high at any point of the reset or the init");

        /* writes: only on a change, a live rail change in two */
        g_exp.regs_written.clear();
        CHECK(exp_write_outputs(&x, EXP_MIR_NSLEEP | EXP_MIR_EN1) && g_exp.regs_written.size() == 1, "one write for a change");
        CHECK(exp_write_outputs(&x, EXP_MIR_NSLEEP | EXP_MIR_EN1) && g_exp.regs_written.size() == 1, "none for no change");
        g_exp.pins.clear();
        exp_write_outputs(&x, EXP_MIR_NSLEEP | EXP_MIR_EN1 | EXP_MIR_IN1);
        CHECK(g_exp.pins.size() == 2 && !(g_exp.pins[0] & EXP_MIR_EN1) && (g_exp.pins[1] & EXP_MIR_IN1),
              "a live bridge changing rail is opened in a write of its own");

        /* INT: the inputs are read back; nFAULT low is seen */
        g_exp.in = (uint16_t)(0xFFFF & ~EXP_MIR_NFAULT);
        CHECK(tca_read_inputs(&x) && !(x.in & EXP_MIR_NFAULT) && (x.in & EXP_PG_5V), "INT read: nFAULT low, power good");

        /* a silent expander: not ok, and its writes fail */
        g_exp.nack = true;
        CHECK(exp_write_outputs(&x, 0) == 0 && x.ok == 0, "no acknowledge: the driver knows");
        CHECK(exp_reset_init(&x) == 0, "and a re-init fails until it answers");
        g_exp.nack = false;
        CHECK(exp_reset_init(&x) == 1 && g_exp.out == 0, "answers again: re-initialised, all low");

        /* the guard: wake, fault, rest, clear through the reset */
        drv_guard_t g; memset(&g, 0, sizeof g); uint32_t t = 100000;
        drv_guard_step(&g, 0, 1, 1, t);
        CHECK(g.awake == 1 && drv_live(&g, t) == 0, "permitted: nSLEEP high, not live until it has woken");
        CHECK(drv_live(&g, t + DRV_WAKE_MS) == 1, "live after the wake time");
        drv_guard_step(&g, 1, 1, 0, t + 1);
        CHECK(g.fault == 0, "nFAULT while waking is not believed");
        t += 100;
        drv_guard_step(&g, 1, 1, 0, t);
        CHECK(g.fault == 1 && drv_live(&g, t) == 0, "nFAULT awake: latched, every bridge open");
        CHECK(drv_guard_step(&g, 1, 1, 0, t + DRV_FAULT_REST_MS) == DRV_NONE, "stick still held: no clear");
        CHECK(drv_guard_step(&g, 1, 1, 1, t + DRV_FAULT_REST_MS - 1) == DRV_NONE, "let go, but inside the rest: no clear");
        CHECK(drv_guard_step(&g, 1, 1, 1, t + DRV_FAULT_REST_MS) == DRV_CLEAR && g.clears == 1 && g.awake == 0,
              "rested and let go: cleared, asleep through the reset");

        /* the host's clear is the boot path: one more reset pulse, nSLEEP low through it */
        int r0 = g_exp.resets; g_exp.pins.clear();
        exp_reset_init(&x);
        bool slept = !g_exp.pins.empty();
        for (uint16_t p : g_exp.pins) if (p & EXP_MIR_NSLEEP) slept = false;
        CHECK(g_exp.resets == r0 + 1 && slept, "the clear pulses RESET and holds nSLEEP low (R35)");

        t += DRV_FAULT_REST_MS + 10;
        drv_guard_step(&g, 0, 1, 1, t);
        CHECK(g.awake == 1 && drv_live(&g, t + DRV_WAKE_MS) == 1, "woken again, live");
        for (int k = 0; k < DRV_FAULT_MAX_CLEARS + 2; k++) {        /* a hard short: it comes back */
            t += 100; drv_guard_step(&g, 1, 1, 1, t);
            t += DRV_FAULT_REST_MS; drv_guard_step(&g, 1, 1, 1, t);
            t += 10; drv_guard_step(&g, 0, 1, 1, t);
        }
        CHECK(g.clears == DRV_FAULT_MAX_CLEARS && g.fault == 1 && g.awake == 0 && drv_live(&g, t) == 0,
              "after three clears it gives up: asleep, mirrors off");
        drv_guard_step(&g, 1, 0, 1, t + 5);
        CHECK(g.clears == 0 && g.fault == 0 && g.awake == 0, "key cycled: tries refilled, asleep");
        drv_guard_step(&g, 0, 1, 1, t + 10);
        CHECK(g.awake == 1, "and wakes on the next permit");
    }

    /* ================= 17. CAN STB held low (SN26, D-452) ================= */
    {
        exp_model_fresh();
        tca9539_t x; memset(&x, 0, sizeof x);
        exp_hal_reset(1);
        CHECK(!(exp_pin_levels() & EXP_CAN_STB), "in reset STB sits on its pull-down: normal mode");
        exp_reset_init(&x);
        CHECK(!(g_exp.cfg & EXP_CAN_STB) && !(g_exp.out & EXP_CAN_STB), "after init STB is an output, driven low");
        bool low = true; uint32_t seed = 31337;
        for (int i = 0; i < 20000 && low; i++) {
            seed = seed * 1103515245u + 12345u;
            exp_write_outputs(&x, (uint16_t)(seed >> 8));           /* any word at all, STB bit included */
            if (exp_pin_levels() & EXP_CAN_STB) low = false;
            if (g_exp.cfg != EXP_INPUTS) low = false;
        }
        CHECK(low, "20k arbitrary output words: STB never leaves low, no port changes direction");
        mirror_out_t mo; memset(&mo, 0, sizeof mo);
        CHECK(!(exp_word(&mo, 0, 0) & EXP_CAN_STB) && !(exp_word(&mo, 1, 1) & EXP_CAN_STB),
              "asleep or awake, the DCU's word keeps STB low");
    }

    /* ================= 18. the logic rows' DCU terms (Y8, logic_vectors.h) =================
     * Three PMU logic rows read a term only the DCU's 0x400 frame can raise: MOTOR_BUS's
     * window_req (any of the four window keys), DEFOG's panel_defog (the defog key, D-350)
     * and ACCESSORY's release_pulse (raised by the hatch or fuel-door release, D-354). For
     * every generated vector that assigns one of them, the real key path (debounce, wake,
     * release select, 0x400 sender) is driven and the frame must carry the term exactly
     * when the vector says - every key of the term raises it, no other key does. The rows
     * themselves are the PMU's: test_suite section 14 holds the simulator to them. */
    {
        struct { const char *term; uint16_t keys; } dcuTerm[] = {
            { "window_req",    PK_WIN_DRV_UP | PK_WIN_DRV_DN | PK_WIN_PASS_UP | PK_WIN_PASS_DN },
            { "panel_defog",   PK_DEFOG },
            { "release_pulse", PK_HATCH | PK_FUEL_DOOR },
        };
        const int NT = (int)(sizeof dcuTerm / sizeof dcuTerm[0]);
        auto frame_down = [](uint16_t raw) -> uint16_t {
            panel_t p; memset(&p, 0, sizeof p);
            p.stopped = 1;                 /* a release only with the car stopped (D-465, section 8) */
            keys_tx_t tx; memset(&tx, 0, sizeof tx);
            panel_keys_t f; memset(&f, 0, sizeof f);
            uint16_t down = 0, held = 0; uint32_t t = 1000;
            for (int i = 0; i < 10; i++, t += 5) panel_keys_step(&p, raw, 1, t, &down, &held);
            panel_frame_due(&tx, down, held, t, &f);
            return f.down;
        };
        for (int d = 0; d < NT; d++) {
            bool named = false;
            for (int k = 0; k < LV_TERMS; k++) if (!strcmp(LV_TERM[k], dcuTerm[d].term)) named = true;
            char m[96]; snprintf(m, sizeof m, "the record's logic rows still read %s", dcuTerm[d].term);
            CHECK(named, m);
        }
        int pairs = 0;
        for (int v = 0; v < LV_VECTORS; v++) {
            const lv_vector_t &V = LV_VECTOR[v];
            for (int j = 0; j < LV_MAXV && V.term[j] >= 0; j++)
                for (int d = 0; d < NT; d++) {
                    if (strcmp(LV_TERM[V.term[j]], dcuTerm[d].term)) continue;
                    const uint16_t set = dcuTerm[d].keys;
                    bool ok = true;
                    if (V.tval[j]) {
                        for (int b = 0; b < PK_COUNT; b++)
                            if ((set & (1u << b)) && !(frame_down((uint16_t)(1u << b)) & set)) ok = false;
                    } else {
                        if (frame_down(0) & set) ok = false;
                        for (int b = 0; b < PK_COUNT; b++)
                            if (!(set & (1u << b)) && (frame_down((uint16_t)(1u << b)) & set)) ok = false;
                    }
                    char m[128];
                    snprintf(m, sizeof m, "%s vector %d: 0x400 carries %s = %d", LV_ROW[V.row].id, v,
                             dcuTerm[d].term, V.tval[j]);
                    CHECK(ok, m);
                    pairs++;
                }
        }
        CHECK(pairs > 0, "the logic vectors exercise at least one DCU term");
        printf("   logic vectors: %d DCU term assignments checked against the 0x400 key path\n", pairs);
    }

    printf("\n passed %d   failed %d\n", g_pass, g_fail);
    printf(g_fail ? " DCU TESTS FAILED\n" : " ALL DCU TESTS PASSED\n");
    return g_fail ? 1 : 0;
}
