# -*- coding: utf-8 -*-
"""harness.py — the master harness sheet, rendered from data/ (D-275).

One model of the whole electrical system — battery to part to ground, every conductor, every connector
pin, every fuse and relay terminal — built from the same tables as every other document, so it cannot
disagree with them and never goes stale; six WireViz drawings are cut from it (D-275, D-276):
  HARNESS     the master sheet, everything
  LEG-L1..L4  one per leg, beginning to end: the leg's post housings on the left (each cavity labelled with
              what feeds it at the node), the leg conductors, the parts, the grounds — L4 also carries the
              backbone from the battery to the dash busbar and the sill node
  DASH-NODE   the PMU, blocks, relays, wake strip, the node conductors to every post housing, the drops
`tools/rx7.py build` calls `pre_build()` after the checks pass: it always writes the .yml files in
`01-DESIGN/diagrams/`, and renders .svg / .html (WireViz + Graphviz) when both are installed.  A stamp per
sheet records the YAML hash it was rendered from; `{{harness_status}}` prints whether the drawings are current.

Endpoints come from structured cells only:
  cavities.src            box-side source of every cavity (pin, fuse, relay terminal, wake input, ground, post link, tap)
  devices.terminals       device end of every leg conductor ("<terminal> → <cavity>", "<terminal> → <ground node>")
  relays.c86/c85/c30/c87  relay terminals not already named by a cavity
  fuses.fed_from          inline-fuse inputs
  cables.run              the power backbone chains
  grounds.return          star studs → chassis
Anything that cannot be resolved lands in the build output as a `harness: …` line, never silently.
"""
import csv, hashlib, json, os, re, shutil
from collections import OrderedDict
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "01-DESIGN" / "diagrams"
NAME = "HARNESS"

COL = {"RED": "RD", "ORN": "OG", "BLK": "BK", "GRY": "GY", "BLU": "BU", "PNK": "PK", "YEL": "YE", "GRN": "GN", "WHT": "WH", "shielded": "GY"}
STATE_COL = {"LIVE": "GN", "CAPPED": "YE", "RESERVED": "OG", "PLUG": "GY"}
CAV = r"(L\d-(?:[PMS]\d?|BLW|NZL|OAT|CMF|WIN|MOD|RDR)|D[12]|DP-[A-Z]+(?:-[A-Z])?) (\d+)"
GROUND_NODES = [("front star", "FRONT-STAR"), ("rear star", "REAR-STAR"), ("dash ground", "DASH-GND"), ("gnd bus", "GND-BUS"),
                ("block ground", "BLOCK"), ("column ground", "COLUMN-GND"), ("roof-rail ground", "ROOF-GND"), ("chassis", "CHASSIS"),
                ("→ block", "BLOCK"), ("ground", "BODY")]
BLOCK_A = ["F2", "F3", "F19", "F13"]; BLOCK_B = ["F1"]
INLINE = {"F12", "F15", "F16", "F20"}; MIDI = {"F17", "F18"}; SILL_F = {"F8", "F9", "F14"}


def rp(term):
    """Relay pin id: 30/85/86/87 as ints, 87a as text."""
    return int(term) if term.isdigit() else term


def rd(name):
    with open(HERE / "data" / f"{name}.csv", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def awg_of(s, default=16):
    """'16', '16 tw', '12 / 16', '1/0', 'O1 splice (12 AWG)' → the gauge as an int (1/0 → 0)."""
    s = s or ""
    if re.search(r"1/0", s):
        return 0
    m = re.search(r"(\d+)\s*AWG", s) or re.match(r"\s*(\d+)", s)
    return int(m.group(1)) if m else default


class Sheet:
    def __init__(self):
        self.conn = OrderedDict()
        self.wires = []          # (group, gauge, (c, p), (c, p), colour, label)
        self.problems = []
        self.leg_covered = set() # cavity ids that have a device-end wire
        self.srcl = {}           # (housing, cav) -> what feeds the cavity at the node, for the leg sheets

    # ── connectors
    def connector(self, name, type_, subtype="", notes="", simple=False, pins=None, labels=None, colors=None):
        if name not in self.conn:
            self.conn[name] = {"type": type_, "subtype": subtype, "notes": notes, "simple": simple,
                               "pins": list(pins or []), "labels": list(labels or []), "colors": list(colors or [])}
        return self.conn[name]

    def pin(self, name, pid, label=None, color=None):
        c = self.conn[name]
        if c["simple"]:
            return
        if pid not in c["pins"]:
            c["pins"].append(pid); c["labels"].append(label or str(pid)); c["colors"].append(color or "")
        elif label and c["labels"][c["pins"].index(pid)] == str(pid):
            c["labels"][c["pins"].index(pid)] = label

    # ── wires
    def wire(self, group, a, b, gauge, colour, label="", tag=""):
        if a is None or b is None:
            return
        for c, p in (a, b):
            if c not in self.conn:
                self.problems.append(f"no connector {c!r} for wire {label!r}"); return
            if p is not None:
                self.pin(c, p)
        self.wires.append((group, int(gauge), a, b, colour, label, tag))

    # ── YAML
    def yaml(self, title, description, splines="spline"):
        q = json.dumps
        L = ["# Generated by tools/rx7.py build from data/ — never edit; the drawing is rendered from this file.",
             "metadata:", f"  title: {q(title)}", f"  description: {q(description)}",
             "options:", "  color_mode: short", "  mini_bom_mode: true", "  fontname: Segoe UI", "  bgcolor: '#FFFFFF'",
             "tweak:", "  override:", f"    graph: {{ranksep: '1.0', nodesep: '0.18', splines: '{splines}'}}", "connectors:"]
        for n, c in self.conn.items():
            L.append(f"  {q(n)}:")
            L.append(f"    type: {q(c['type'])}")
            if c["subtype"]: L.append(f"    subtype: {q(c['subtype'])}")
            if c["notes"]: L.append(f"    notes: {q(c['notes'])}")
            if c["simple"]:
                L.append("    style: simple")
            else:
                L.append(f"    pins: [{', '.join(q(p) for p in c['pins'])}]")
                L.append(f"    pinlabels: [{', '.join(q(l) for l in c['labels'])}]")
                if any(c["colors"]):
                    L.append(f"    pincolors: [{', '.join(q(x or 'WH') for x in c['colors'])}]")
        # bundles: one per (group, gauge)
        bundles = OrderedDict()
        for w in self.wires:
            bundles.setdefault((w[0], w[1]), []).append(w)
        L.append("cables:")
        for (g, ga), ws in bundles.items():
            L.append(f"  {q(f'{g} · {ga} AWG' if ga else f'{g} · 1/0')}:")
            L.append("    category: bundle")
            L.append(f"    gauge: {ga} AWG")
            L.append(f"    colors: [{', '.join(w[4] for w in ws)}]")
            L.append(f"    wirelabels: [{', '.join(q(w[5]) for w in ws)}]")
        L.append("connections:")
        for (g, ga), ws in bundles.items():
            cab = f"{g} · {ga} AWG" if ga else f"{g} · 1/0"
            for i, w in enumerate(ws, 1):
                a, b = w[2], w[3]
                L.append(f"  - - {q(a[0])}: [{q(a[1])}]" if a[1] is not None else f"  - - {q(a[0])}")
                L.append(f"    - {q(cab)}: [{i}]")
                L.append(f"    - {q(b[0])}: [{q(b[1])}]" if b[1] is not None else f"    - {q(b[0])}")
        return "\n".join(L) + "\n"


def build_sheet():
    S = Sheet()
    pins = rd("pins"); cavs = rd("cavities"); hous = rd("housings"); devs = rd("devices"); rels = rd("relays"); fus = rd("fuses"); cabs = rd("cables"); grounds = rd("grounds")
    H = {h["code"]: h for h in hous}
    CAVR = {c["id"]: c for c in cavs}
    pin_of = {p["ch"]: p["pin"] for p in pins if p["ch"]}
    FUSE_RATING = {f["id"]: f["rating"] for f in fus}

    # ── the fixed hardware
    S.connector("BATTERY", "Ionic S9 LiFePO4", "cargo bin", pins=["+", "−"], labels=["+ post (booted)", "− post (booted)"])
    S.connector("CLASS-T", "Class-T 150 A", "at the battery +", pins=["in", "out"], labels=["battery +", "2 AWG to the dash post"])
    S.connector("MRBF", "MRBF 200 A", "on the battery +", pins=["in", "out"], labels=["battery +", "1/0 starter run"])
    S.connector("DISCONNECT", "Master disconnect", "battery negative (D-245)", pins=["in", "out"], labels=["battery −", "rear ground stud"])
    S.connector("STARTER", "Starting motor A-01", "engine", pins=["B+", "S"], labels=["B+ stud", "S terminal"])
    S.connector("ALTERNATOR", "Alternator A-08 / A-09", "engine", pins=["B+", "BW", "WB"], labels=["B+ ring (WR)", "BW excitation", "WB lamp sense"])
    S.connector("F17", "MIDI 30 A — START-RLY", "at the starter stud", pins=["in", "out"], labels=["starter B+ stud", "K9 30"])
    S.connector("F18", "MIDI 100 A — ALTERNATOR", "at the starter stud", pins=["in", "out"], labels=["starter B+ stud", "alternator B+"])
    S.connector("BLOCK", "Engine block", "ground node L1", simple=True)
    S.connector("CHASSIS", "Chassis — bare metal", "every star stud lands here", simple=True)
    S.connector("FRONT-STAR", "Front star stud", "radiator support", simple=True)
    S.connector("REAR-STAR", "Rear ground stud", "cargo bin", simple=True)
    S.connector("DASH-GND", "Dash chassis star", "behind the dash", simple=True)
    S.connector("SILL-STUD", "Sill ground stud", "sill node", simple=True)
    S.connector("COLUMN-GND", "Column ground", "steering column", simple=True)
    S.connector("ROOF-GND", "Roof-rail ground", "headliner", simple=True)
    S.connector("BODY", "Body ground at the device", "factory bracket / latch", simple=True)
    S.connector("BUSBAR", "Always-hot busbar", "dash node — covered", simple=True)
    S.connector("GND-BUS", "GND bus", "dash node", simple=True)
    S.connector("BLOCK-A", "Fuse block A — busbar fed", "dash node", pins=["IN"] + BLOCK_A, labels=["input"] + BLOCK_A)
    S.connector("BLOCK-B", "Fuse block B — K11 fed", "dash node", pins=["IN"] + BLOCK_B + ["spare 2", "spare 3", "spare 4"], labels=["input"] + BLOCK_B + ["spare (phase-2 sensor supply)", "spare", "spare"])
    for f in fus:
        lab = f"{f['id']} {f['rating']} {f['label']}".strip()
        if f["id"] in BLOCK_A: S.pin("BLOCK-A", f["id"], lab)
        if f["id"] in BLOCK_B: S.pin("BLOCK-B", f["id"], lab)
        if f["id"] in INLINE: S.connector(f["id"], f"Inline {f['rating']} — {f['label']}", "dash node, sealed holder", pins=["in", "out"], labels=["in", "out"])
    S.connector("SILL-F", "Sill fuse positions F8 · F9 · F14", "labelled, no holders this build", pins=["F8/F9 feed", "F8", "F9", "F14 feed", "F14"], labels=["window bus in (L4-P 3)", "F8 WIN-DRV", "F9 WIN-PASS", "comfort in (L4-P 4)", "F14 MIRROR-HEAT"])
    S.connector("WAKE", "Wake strip — 8-position barrier, six 1N5819", "dash node", pins=[1, 2, 3, 4, 5, 6, "rail"], labels=["ACC", "RUN", "door stage", "horn/hazard/wink stage", "O22 latch", "brake", "common rail → pin 7"])
    S.connector("SENSE", "Sense stages ×2 (2N3904)", "dash node perfboard", pins=["A6 node", "A8 node", "F3 rail", "emitters", "out 3", "out 4"], labels=["A6 node in", "A8 node in", "F3 rail", "emitters → GND bus", "stage 1 out", "stage 2 out"])
    S.connector("BIAS", "Bias resistors + oil-node pull-up", "dash node perfboard", pins=["A15", "A16", "OIL"], labels=["100 kΩ → A15", "100 kΩ → A16", "100 Ω 1 W → oil node (D-260)"])
    S.connector("CAN2-TERM", "CAN2 terminator 120 Ω", "capped in the engine bay", pins=["H", "L"], labels=["H", "L"])
    # PMU
    S.connector("PMU", "ECUMaster PMU-24 DL", "39-way SICMA + stud")
    order = sorted([p for p in pins if p["pin"] != "STUD"], key=lambda p: int(p["pin"]))
    S.pin("PMU", "STUD", "+12V BATT")
    for p in order:
        S.pin("PMU", int(p["pin"]), f"{p['ch']} {p['name']}".strip(), STATE_COL.get(p["state"], ""))
    # relays
    for k in rels:
        where = "sill node" if k["location"] == "Sill node" else "engine bay" if "fender" in k["location"] else "dash node"
        S.connector(k["id"], f"{k['id']} {k['function']}"[:70], f"{where} · {k['type'] or 'empty socket'}"[:60], pins=[30, 85, 86, 87, "87a"], labels=["30", "85", "86", "87", "87a"])
    # housings
    for h in hous:
        sub = {"Dash post": "dash post"}.get(h["where"], h["where"].lower())
        if h["box_side"].startswith("DT13"): sub = "on the ICU board — DT13 header"
        S.connector(h["code"], f"{h['leg_side']} ↔ {h['box_side']}", sub, notes=h["note"][:90])
    for c in cavs:
        st = c["state"]
        lab = c["circuit"] if c["circuit"] else "— plug"
        if st != "LIVE": lab += f" [{st}]"
        S.pin(c["housing"], int(c["cav"]), lab, STATE_COL[st])

    # ── helpers
    def leg_of(code):
        return H[code]["leg"].split()[0] if H[code]["leg"].startswith("L") else "Drop"

    def is_post(code):
        return H[code]["where"] == "Dash post"

    def fuse_ep(fid, side="out"):
        if fid in BLOCK_A: return ("BLOCK-A", fid)
        if fid in BLOCK_B: return ("BLOCK-B", fid)
        if fid in INLINE or fid in MIDI: return (fid, side)
        if fid in SILL_F: return ("SILL-F", fid)
        return None

    def ground_ep(text):
        t = text.lower()
        for key, node in GROUND_NODES:
            if key in t: return (node, None)
        return None

    def token_ep(tok, side="out"):
        """A structured source token → (connector, pin)."""
        tok = tok.strip()
        m = re.fullmatch(r"([OA]\d+|CAN[12][HL])", tok)
        if m: return ("PMU", int(pin_of[tok]))
        m = re.fullmatch(r"(F\d+)", tok)
        if m: return fuse_ep(tok, side)
        m = re.fullmatch(r"(K\d+) (30|85|86|87|87a)", tok)
        if m: return (m.group(1), rp(m.group(2)))
        m = re.fullmatch(r"WAKE (\d)", tok)
        if m: return ("WAKE", int(m.group(1)))
        m = re.fullmatch(CAV, tok)
        if m: return (m.group(1), int(m.group(2)))
        if tok == "GND": return ("GND-BUS", None)
        if tok == "SILL-GND": return ("SILL-STUD", None)
        m = re.fullmatch(r"K(\d)/K(\d)", tok)
        if m: return ("K" + m.group(1), 30)
        return None

    # ── 1. the backbone, from cables.csv chains
    NAMES = [("battery +", ("BATTERY", "+")), ("battery −", ("BATTERY", "−")), ("class-t", ("CLASS-T", None)), ("dp-bat", ("BUSBAR", None)),
             ("mrbf", ("MRBF", None)), ("starter b+ stud", ("STARTER", "B+")), ("starter s terminal", ("STARTER", "S")), ("master disconnect", ("DISCONNECT", None)),
             ("rear ground stud", ("REAR-STAR", None)), ("engine block", ("BLOCK", None)), ("chassis strap", ("CHASSIS", None)), ("alternator b+", ("ALTERNATOR", "B+")),
             ("f18", ("F18", None)), ("f17", ("F17", None)), ("k9 30", ("K9", 30)), ("k9 87", ("K9", 87)), ("busbar", ("BUSBAR", None)), ("pmu stud", ("PMU", "STUD"))]
    PASS = {"CLASS-T", "MRBF", "DISCONNECT", "F17", "F18"}
    for cb in cabs:
        chain = [s.strip().lower() for s in re.split(r"→", re.sub(r"\(.*?\)|—.*$", "", cb["run"]))]
        eps = []
        for name in chain:
            ep = next((e for k, e in NAMES if name.startswith(k)), None)
            if not ep: S.problems.append(f"backbone {cb['id']}: unknown node {name!r}"); break
            eps.append(ep)
        for a, b in zip(eps, eps[1:]):
            a2 = (a[0], "out") if a[0] in PASS else a
            b2 = (b[0], "in") if b[0] in PASS else b
            S.wire("BACKBONE", a2, b2, awg_of(cb["awg"]), COL[cb["colour"]], f"{cb['id']} {cb['ft']} ft", tag=cb["id"])

    # ── 2. the dash node's fixed conductors
    S.wire("DASH-NODE", ("BUSBAR", None), ("BLOCK-A", "IN"), 10, "RD", "block A input")
    S.wire("DASH-NODE", ("PMU", 25), ("GND-BUS", None), 10, "BK", "pin 25 ≤ 6 in")
    S.wire("DASH-NODE", ("WAKE", "rail"), ("PMU", 7), 16, "BU", "+12V SW · 10 kΩ bleed to GND")
    S.wire("DASH-NODE", ("PMU", 8), ("WAKE", 5), 16, "RD", "O22 keep-alive")
    for i, pid in enumerate(("A15", "A16", "OIL")):
        S.wire("DASH-NODE", ("PMU", 15), ("BIAS", pid), 16, "PK", "+5 V")
    S.wire("DASH-NODE", ("BIAS", "A15"), ("PMU", 35), 16, "GY", "100 kΩ bias"); S.wire("DASH-NODE", ("BIAS", "A16"), ("PMU", 22), 16, "GY", "100 kΩ bias")
    S.wire("DASH-NODE", ("BIAS", "OIL"), ("DP-ICU-B", 2), 16, "GY", "100 Ω 1 W excitation (D-260)")
    S.wire("DASH-NODE", ("PMU", 32), ("DP-ICU-B", 2), 16, "GY", "A7 tap on the oil node (N45)")
    S.wire("DASH-NODE", ("PMU", 18), ("SENSE", "A6 node"), 16, "GY", "100 kΩ base network"); S.wire("DASH-NODE", ("PMU", 19), ("SENSE", "A8 node"), 16, "GY", "100 kΩ base network")
    S.wire("DASH-NODE", ("BLOCK-A", "F3"), ("SENSE", "F3 rail"), 16, "PK", "pull-ups"); S.wire("DASH-NODE", ("SENSE", "emitters"), ("GND-BUS", None), 16, "BK", "")
    S.wire("DASH-NODE", ("SENSE", "out 3"), ("WAKE", 3), 16, "BU", "door stage"); S.wire("DASH-NODE", ("SENSE", "out 4"), ("WAKE", 4), 16, "BU", "horn/hazard/wink stage")
    S.wire("DASH-NODE", ("GND-BUS", None), ("DASH-GND", None), 10, "BK", "G14 dash star")
    for f in fus:
        if f["id"] in INLINE:
            ep = token_ep(f["fed_from"].split()[0])
            S.wire("DASH-NODE", ep, (f["id"], "in"), 16, "RD", f"{f['id']} feed")
    # relays: terminals that no cavity names
    for k in rels:
        cg = awg_of(k["c30"], 14) if "AWG" in k["c30"] else 14
        grp = "DASH-NODE" if k["location"] == "Dash node" else "SILL-NODE" if k["location"] == "Sill node" else "LEG-L1"
        for term, txt, g in (("86", k["c86"], 16), ("85", k["c85"], 16), ("30", k["c30"], cg), ("87", k["c87"], cg), ("87a", k["c87a"], cg)):
            if not txt: continue
            mc = re.match(CAV, txt)
            if mc:  # a cavity names this terminal; if the relay is the cavity's far end (K9 in the bay), the leg wire is ours to draw
                cav = CAVR[f"{mc.group(1)} {mc.group(2)}"]
                if f"{k['id']} {term}" not in cav["src"]:
                    S.wire(grp, (mc.group(1), int(mc.group(2))), (k["id"], rp(term)), awg_of(cav["awg"]), COL.get(cav["colour"], "GY"), f"{cav['id']} → {k['id']} {term}"); S.leg_covered.add(cav["id"])
                continue
            t = txt.lower(); ep = None; col = "RD"
            if re.match(r"[OA]\d+", txt): ep = ("PMU", int(pin_of[txt.split()[0]]))
            elif t.startswith("gnd bus"): ep, col = ("GND-BUS", None), "BK"
            elif t.startswith("block ground"): ep, col = ("BLOCK", None), "BK"
            elif t.startswith("busbar"): ep = ("BUSBAR", None)
            elif t.startswith("block b input"): ep = ("BLOCK-B", "IN")
            elif t.startswith(("f17", "starter")): continue          # the backbone draws these
            else: S.problems.append(f"relay {k['id']} {term}: {txt!r} not resolved"); continue
            if term in ("86", "30", "87") and col == "RD" and ep[0] == "PMU" and g == 14: col = "OG"
            if term == "87": S.wire(grp, (k["id"], rp(term)), ep, g, col, f"{k['id']} {term}")
            else: S.wire(grp, ep, (k["id"], rp(term)), g, col, f"{k['id']} {term}")

    # ── 3. every cavity's box side
    for c in cavs:
        st, code, n = c["state"], c["housing"], int(c["cav"])
        if st == "PLUG": continue
        col = COL.get(c["colour"], "GY"); ga = awg_of(c["awg"]); post = is_post(code); drop = code.startswith("DP-")
        leg_grp = f"LEG-{leg_of(code)}" if leg_of(code) != "Drop" else "DASH-NODE"
        node_grp = "DASH-NODE" if (post or drop) else "SILL-NODE" if H[code]["where"] == "Sill node" else leg_grp
        srcl = []
        if st == "RESERVED" and not c["src"]:
            S.wire("DASH-NODE", ("BLOCK-B", "spare 2"), (code, n), ga, col, f"{c['id']} (RESERVED, N68)"); S.srcl[(code, n)] = "block B spare position"; continue
        for tok in [t.strip() for t in c["src"].split("+") if t.strip()]:
            if tok.startswith("tap "):
                m = re.fullmatch(CAV, tok[4:]); src = (m.group(1), int(m.group(2)))
                S.wire(leg_grp, src, (code, n), ga, col, "tap"); S.leg_covered.add(tok[4:]); srcl.append(f"tap on {tok[4:]}"); continue
            m = re.fullmatch(CAV, tok)
            if m:
                src = (m.group(1), int(m.group(2)))
                if post or drop: S.wire("DASH-NODE", src, (code, n), ga, col, "post link"); srcl.append(f"{tok} (post link)")
                else: S.wire(leg_grp, src, (code, n), ga, col, ""); S.leg_covered.add(tok)
                continue
            ep = token_ep(tok)
            if ep is None: S.problems.append(f"cavity {c['id']}: source {tok!r} not resolved"); continue
            lab = c["src_note"]
            S.wire(node_grp, ep, (code, n), ga, col, lab)
            if ep[0] == "SILL-F": S.leg_covered.add(c["id"])
            if ep[0] == "PMU": srcl.append(f"{tok} pin {ep[1]}" + (f" {lab}" if lab else ""))
            elif ep[0] in ("BLOCK-A", "BLOCK-B", "SILL-F") or ep[0] in INLINE or ep[0] in MIDI: srcl.append(f"{tok} {FUSE_RATING.get(tok, '')}".strip())
            elif ep[0] == "GND-BUS": srcl.append("GND bus")
            elif ep[0] == "SILL-STUD": srcl.append("sill stud")
            elif ep[0] == "WAKE": srcl.append(f"wake strip {ep[1]}")
            else: srcl.append(tok)
        if not c["src"] and st == "CAPPED": srcl.append("capped at the post")
        if srcl: S.srcl[(code, n)] = " + ".join(srcl)

    # ── 4. every cavity's device end, from devices.terminals
    SKIP = {"DV02", "DV03", "DV04", "DV09", "DV17", "DV42", "DV43", "DV45", "DV46"}
    ALIAS = {"DV04": "ALTERNATOR"}
    for d in devs:
        if d["id"] in SKIP and d["id"] not in ALIAS: continue
        cname = ALIAS.get(d["id"], d["id"])
        if cname == d["id"]:
            S.connector(cname, f"{d['device']}", d["ident"][:48], notes=f"zone {d['zone']}")
        notes = []
        for line in re.split(r"<br\s*/?>", d["terminals"]):
            line = line.replace("**", "").strip()
            m = re.match(r"^(.*?)\s*(→|←)\s*(.*)$", line)
            if not m: notes.append(line[:60]); continue
            term, rest = m.group(1).strip(), m.group(3)
            if cname == "ALTERNATOR":
                term = "BW" if term.startswith("BW") else "WB" if term.startswith("WB") else None
                if term is None: continue
            for seg in re.split(r";\s*", rest):
                if re.search(r"\b(F17|F18|MRBF)\b", seg): continue
                raw = seg
                seg2 = re.sub(r"\((?!LH\)|RH\))[^)]*\)", "", seg)
                refs = [(a, int(b), (mk or "").strip()) for a, b, mk in re.findall(CAV + r"(\s*\((?:LH|RH)\))?", seg2)]
                kohm = re.findall(r"([\d.]+ kΩ)", seg2); diode = "1N5819" in seg2
                lab = " + ".join(kohm) + (" + 1N5819" if diode else "")
                if re.search(r"\bsplice", seg2): lab = (lab + " splice").strip()
                if re.search(r"\bbranch", seg2) and not kohm: lab = (lab + " branch").strip()
                if re.search(r"\bdirect\b", seg2): lab = (lab + " direct").strip()
                mb = re.search(r"(\d+) AWG branch", raw); ma = re.search(r"(\d+) AWG", raw)
                if refs:
                    for hc, hn, mk in refs:
                        cav = CAVR.get(f"{hc} {hn}")
                        if not cav: S.problems.append(f"{d['id']}: unknown cavity {hc} {hn}"); continue
                        pid = f"{term} {mk}".strip()
                        S.pin(cname, pid, pid)
                        ga = int(mb.group(1)) if mb else int(ma.group(1)) if ma else awg_of(cav["awg"])
                        grp = f"LEG-{leg_of(hc)}" if leg_of(hc) != "Drop" else "DASH-NODE"
                        S.wire(grp, (hc, hn), (cname, pid), ga, COL.get(cav["colour"], "GY"), lab)
                        S.leg_covered.add(cav["id"])
                    continue
                mf = re.search(r"\b(F\d+)\b", seg2)
                if mf and fuse_ep(mf.group(1)):
                    S.pin(cname, term, term); S.wire("DASH-NODE", fuse_ep(mf.group(1)), (cname, term), 16, "RD", mf.group(1)); continue
                if "CAN2" in seg2:
                    S.pin(cname, "CAN H", "AEMnet CAN H"); S.pin(cname, "CAN L", "AEMnet CAN L")
                    S.wire("DASH-NODE", ("PMU", int(pin_of["CAN2H"])), (cname, "CAN H"), 16, "YE", "CAN2 splice"); S.wire("DASH-NODE", ("PMU", int(pin_of["CAN2L"])), (cname, "CAN L"), 16, "GN", "CAN2 splice"); continue
                gep = ground_ep(seg2)
                if gep:
                    S.pin(cname, term, term); ga = int(ma.group(1)) if ma else 16
                    if kohm and gep[0] == "BODY":  # "47 kΩ baseline at the connector to ground" — a resistor to the zone's star, not a body ground
                        gep = ({"L1": "BLOCK", "L2": "FRONT-STAR", "L3": "DASH-GND", "L4": "REAR-STAR"}.get(d["zone"], "BODY"), None)
                    grp = "DASH-NODE" if gep[0] == "GND-BUS" else f"GND-{d['zone']}"
                    S.wire(grp, (cname, term), gep, ga, "BK", (" + ".join(kohm) + " baseline") if kohm else ""); continue
                notes.append(f"{term}: {seg2.strip()}"[:70])
        if notes and cname in S.conn and cname == d["id"]:
            S.conn[cname]["notes"] = (S.conn[cname]["notes"] + " · " + " · ".join(notes))[:200]

    # ── 5. leg ends nothing named: sockets, the sill fuse feeds, the CAN terminator, then the lands_on text
    for c in cavs:
        code = c["housing"]
        if c["state"] not in ("LIVE", "CAPPED") or not is_post(code) or code.startswith("DP-") or c["id"] in S.leg_covered: continue
        n = int(c["cav"]); ga = awg_of(c["awg"]); col = COL.get(c["colour"], "GY"); grp = f"LEG-{leg_of(code)}"
        m = re.search(r"(K\d+) socket, terminal (\d+a?)", c["lands_on"])
        if m: S.wire(grp, (code, n), (m.group(1), rp(m.group(2))), ga, col, "empty socket"); continue
        if c["id"] == "L4-P 3": S.wire(grp, (code, n), ("SILL-F", "F8/F9 feed"), ga, col, "L4-P 3"); continue
        if c["id"] == "L4-P 4": S.wire(grp, (code, n), ("SILL-F", "F14 feed"), ga, col, "L4-P 4"); continue
        if c["id"] in ("L1-S1 9", "L1-S1 10"): S.wire(grp, (code, n), ("CAN2-TERM", "H" if n == 9 else "L"), ga, col, c["id"]); continue
        if c["src"] and all(re.fullmatch(CAV, t.strip()) for t in c["src"].split("+")) and not is_post(code): continue
        far = f"FAR {c['id']}"
        S.connector(far, re.sub(r"\s*\(.*$", "", c["lands_on"])[:60] or "far end", "leg end", simple=True)
        S.wire(grp, (code, n), (far, None), ga, col, c["id"])
        S.problems.append(f"leg end of {c['id']} is prose only — drawn from lands_on")
    # ── 6. star studs → chassis
    for g in grounds:
        m = re.match(r"^(Front star stud|Rear star stud|Sill stud) → chassis", g["return"])
        if m:
            node = {"Front star stud": "FRONT-STAR", "Rear star stud": "REAR-STAR", "Sill stud": "SILL-STUD"}[m.group(1)]
            S.wire(f"GND-{g['zone']}", (node, None), ("CHASSIS", None), awg_of(g["awg"]), "BK", f"{g['id']} {g['ft']} ft")
    # the tach shield note
    S.conn["DP-ICU-B"]["notes"] = (S.conn["DP-ICU-B"]["notes"] + " · tach on cavity 4 is shielded — drain to the GND bus at this end only")[:200]
    return S


# ── the sheets cut from the model (D-276)
REAR_CABLES = {"C01", "C02", "C03", "C04", "C05", "C11"}; BAY_CABLES = {"C06", "C07", "C08", "C09"}
SHEETS = OrderedDict([
    ("HARNESS",   {"title": "the master harness sheet — every conductor, battery to part to ground", "splines": "spline",
                   "keep": lambda g, t: True, "leg_labels": False, "stubs": [], "foreign": {}}),
    ("LEG-L4",    {"title": "L4 · REAR — the rear leg, the sill node and the power backbone to the dash busbar", "splines": "polyline",
                   "keep": lambda g, t: g in ("LEG-L4", "SILL-NODE", "GND-L4", "GND-Sill") or (g == "BACKBONE" and t in REAR_CABLES), "leg_labels": True, "stubs": [],
                   "foreign": {"BUSBAR": "dash node — DASH-NODE sheet", "STARTER": "engine bay — LEG-L1 sheet", "BLOCK": "engine bay — LEG-L1 sheet", "K5": "sill node", "K6": "sill node", "K7": "sill node", "K8": "sill node"}}),
    ("LEG-L3",    {"title": "L3 · DASH — the dash leg, from its post housings to the switches, lamps and branch-end receptacles", "splines": "polyline",
                   "keep": lambda g, t: g in ("LEG-L3", "GND-L3"), "leg_labels": True, "stubs": [], "foreign": {"GND-BUS": "dash node — DASH-NODE sheet"}}),
    ("LEG-L2",    {"title": "L2 · FRONT — the front leg, from its post housings to the lamps, motors and nose receptacles", "splines": "polyline",
                   "keep": lambda g, t: g in ("LEG-L2", "GND-L2"), "leg_labels": True, "stubs": [], "foreign": {}}),
    ("LEG-L1",    {"title": "L1 · ENGINE — the engine leg, the starter and alternator cables in the bay", "splines": "polyline",
                   "keep": lambda g, t: g in ("LEG-L1", "GND-L1") or (g == "BACKBONE" and t in BAY_CABLES), "leg_labels": True,
                   "stubs": [("FROM-BATTERY", "1/0 from the battery + through the MRBF — drawn on the LEG-L4 sheet", ("STARTER", "B+"), 0, "RD", "C04"),
                             ("TO-REAR-STUD", "1/0 cranking return to the rear ground stud — drawn on the LEG-L4 sheet", ("BLOCK", None), 0, "BK", "C11")],
                   "foreign": {}}),
    ("DASH-NODE", {"title": "THE DASH NODE — PMU, blocks, relays, wake strip, the node conductors to every post housing, the drops", "splines": "spline",
                   "keep": lambda g, t: g == "DASH-NODE" or (g == "BACKBONE" and t == "C10"), "leg_labels": False,
                   "stubs": [("FROM-CLASS-T", "2 AWG from the Class-T at the battery — drawn on the LEG-L4 sheet", ("BUSBAR", None), 2, "RD", "C03")], "foreign": {}}),
])


def subset(M, name):
    """Cut one sheet from the model: its wires, the connectors they touch, per-sheet labels and stubs."""
    spec = SHEETS[name]; S = Sheet(); S.problems = []
    wires = [w for w in M.wires if spec["keep"](w[0], w[6])]
    used = {w[2][0] for w in wires} | {w[3][0] for w in wires} | {st[2][0] for st in spec["stubs"]}
    for n, c in M.conn.items():
        if n not in used: continue
        c2 = {k: (list(v) if isinstance(v, list) else v) for k, v in c.items()}
        if n in spec["foreign"]: c2["subtype"] = spec["foreign"][n]
        if spec["leg_labels"] and not n.startswith("DP-") and any((n, p) in M.srcl for p in c2["pins"]):
            c2["labels"] = [f"{lab}  ⟵ {M.srcl[(n, p)]}" if (n, p) in M.srcl else lab for p, lab in zip(c2["pins"], c2["labels"])]
        S.conn[n] = c2
    for sid, text, ep, ga, col, tag in spec["stubs"]:
        S.connector(sid, text, "see the other sheet", simple=True)
        wires.append(("BACKBONE", ga, (sid, None), ep, col, tag, tag))
    if name.startswith("LEG-") and name != "HARNESS":
        # on a leg sheet the housing pins that only exist on the node side would be orphans: hide nothing, WireViz draws them grey
        pass
    # bundles per housing, not per zone: node conductors group by the housing they land on, leg conductors by the
    # housing they leave — small bundle nodes that sit beside their housing, far fewer crossings (D-276)
    regrouped = []
    for w in wires:
        g, a, b = w[0], w[2], w[3]
        if g in ("DASH-NODE", "SILL-NODE"): g = f"{g} → {b[0]}"
        elif g.startswith("LEG-"): g = f"{a[0]} leg" if a[0] in M.conn and not a[0].startswith(("K", "DV", "FAR")) else g
        regrouped.append((g,) + tuple(w[1:]))
    S.wires = regrouped
    return S


def _hash(p):
    return hashlib.sha1(p.read_bytes()).hexdigest()[:12]


def status_line():
    """For {{harness_status}} — are the drawings current with the data?"""
    stale, cur = [], []
    for name in SHEETS:
        y, svg, stamp = OUT / f"{name}.yml", OUT / f"{name}.svg", OUT / f"{name}.stamp"
        if not y.exists(): return "**No harness sheets yet** — run `build`."
        h = _hash(y)
        (cur if svg.exists() and stamp.exists() and stamp.read_text().strip() == h else stale).append(f"`{name}`")
    if not stale: return f"All six sheets are rendered from the current data (`{_hash(OUT / 'HARNESS.yml')}`)."
    return f"**STALE — not re-rendered: {', '.join(stale)}** — install Graphviz and `pip install wireviz` on this machine, then `build` again."


def _renderer():
    if not shutil.which("dot"):  # Graphviz's winget / MSI install does not always reach PATH
        for cand in (r"C:\Program Files\Graphviz\bin", r"C:\Program Files (x86)\Graphviz\bin", str(Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Graphviz" / "bin")):
            if (Path(cand) / "dot.exe").exists():
                os.environ["PATH"] = cand + os.pathsep + os.environ.get("PATH", ""); break
    try:
        from wireviz import wireviz as wv
    except ImportError:
        return None
    return wv if shutil.which("dot") else None


def pre_build(project, db):
    OUT.mkdir(parents=True, exist_ok=True)
    M = build_sheet()
    lines = [f"harness: {len(M.conn)} connectors · {len(M.wires)} conductors in the model"]
    for p in M.problems: lines.append(f"harness: {p}")
    wv = _renderer(); todo = []
    for name, spec in SHEETS.items():
        S = subset(M, name)
        y = OUT / f"{name}.yml"; y.write_text(S.yaml(f"RX-7 FB — electrical build · {spec['title']}", f"Rendered from data/ by tools/rx7.py build (D-275, D-276)", spec["splines"]), encoding="utf-8", newline="\n")
        h = _hash(y); stamp = OUT / f"{name}.stamp"
        if stamp.exists() and stamp.read_text().strip() == h and (OUT / f"{name}.svg").exists(): continue
        todo.append((name, y, h, stamp, len(S.conn), len(S.wires)))
    if not todo:
        lines.append("harness: all six drawings already current"); return lines
    if wv is None:
        lines.append(f"harness: !! NOT RENDERED ({', '.join(t[0] for t in todo)}) — needs Graphviz (dot on PATH) and `pip install wireviz`; marked STALE"); return lines
    for name, y, h, stamp, nc, nw in todo:
        try:
            wv.parse(y, output_formats=("html", "svg"), output_dir=OUT, output_name=name)
        except Exception as e:  # noqa: BLE001 — a rendering failure must be loud, not fatal to the build
            lines.append(f"harness: !! wireviz failed on {name} — {str(e)[:140]}"); continue
        stamp.write_text(h); lines.append(f"harness: rendered {name}.svg + .html — {nc} connectors · {nw} conductors ({h})")
    return lines


if __name__ == "__main__":
    for l in pre_build(HERE, None): print(l)
