# -*- coding: utf-8 -*-
"""migrate_v2.py — one-time: QUESTIONS.md / DECISIONS.md / §0 / banners → data (system v2).

    python tools/migrate_v2.py <project-name> [--dry]

Writes data/questions.csv + data/questions/*.md, data/decisions.csv + data/decisions/*.md,
data/work.csv (merged with an existing one), data/log.csv, data/project.csv, and the three
templates (QUESTIONS.md, DECISIONS.md, LOG.md). The old prose files are left in place and
overwritten by the next build. Archived beside the tree's other migration scripts afterwards.
"""
import csv, io, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import rx7  # noqa: E402

NAME = sys.argv[1]
DRY = "--dry" in sys.argv
P = rx7.find_project(NAME)
D = P / "data"
RANGES = {"electrical-build": (1, 299), "luxury-package": (300, 399), "engine-swap": (400, 499)}
LO, HI = RANGES[P.name]
KIND = {"electrical-build": "electrical", "luxury-package": "electronics", "engine-swap": "mechanical"}[P.name]
PHASE = {"electrical-build": "PLANNING", "luxury-package": "PLANNING", "engine-swap": "PROPOSED"}[P.name]
GOAL = {
    "electrical-build": "Replace the factory electrical system: PMU-24 DL, rear lithium battery, four modular harness legs, every switch a ladder; the car drives on it before anything else joins",
    "luxury-package": "Everything the car gets after it drives on the new harness — bezel and dash plastics, DCU and panel, blower, seats, mirrors, windows, lighting second pass, radar",
    "engine-swap": "Everything that changes with the engine — the engine leg rebuilt around the new engine, ECU, fuel, transmission, axle, A/C",
}[P.name]

ID = r"[A-Z]{1,2}-\d{3}"
HEAD = re.compile(r"^\*\*(" + ID + r")((?:\s*/\s*" + ID + r")*)\s*(?:[·\-—–]\s*)?(.*?)\*\*(.*)$")
out_files = {}


def w(path, text):
    out_files[path] = text


def csv_text(header, rows):
    o = io.StringIO(); wr = csv.writer(o, lineterminator="\n"); wr.writerow(header); wr.writerows(rows); return o.getvalue()


def first_date(s):
    m = re.search(r"\b(20\d\d-\d\d-\d\d)", s)
    return m.group(1) if m else ""


# ------------------------------------------------------------------ QUESTIONS.md
qtext = (P / "QUESTIONS.md").read_text(encoding="utf-8")
if "Generated by `tools/rx7.py build`" in qtext:
    raise SystemExit("QUESTIONS.md is already a rendered file — the migration has run; do not run it twice")
lines = qtext.splitlines()

questions, bodies, work, logrows = [], {}, [], []
seen = set()
sec = "1"
section_intro = {}      # section code -> intro prose lines
section_heads = {}      # section code -> heading line
preamble = []           # everything before the first banner / §0 heading
in_pre = True
i = 0
cur_block, cur_block_title = "", ""
mode = None             # None | "0" | "packets" | "closed" | "moved"
closed_on = ""
intro_buf = []


def flush_intro():
    if sec not in section_intro:
        section_intro[sec] = [l for l in intro_buf]


while i < len(lines):
    l = lines[i]
    m_h = re.match(r"^(#{1,2})\s+(\d[a-z]?)\s*·\s*(.*)$", l)
    if l.startswith("> **") and in_pre:
        # banner → log row
        m = re.match(r"^> \*\*(\d{4}-\d{2}-\d{2})([a-z]?)\.\*\*\s*(.*)$", l)
        if m:
            ids = " ".join(dict.fromkeys(re.findall(ID, m.group(3))))
            summ = m.group(3).replace("**", "")
            wf = "repair" if summ.startswith("Repair") else "answers" if summ.lower().startswith("answer cycle") else "session"
            logrows.append([m.group(1), m.group(2), wf, ids, summ])
        i += 1; continue
    if m_h:
        in_pre = False
        code, title = m_h.group(2), m_h.group(3)
        if code == "0":
            mode = "0"
        elif code == "3":
            mode = "closed"
        elif code == "4":
            mode = "moved"
        else:
            if mode == "packets":
                flush_intro()
            mode = "packets"; sec = code; intro_buf = []; section_heads[sec] = l
        i += 1; continue
    if in_pre and HEAD.match(l):
        in_pre = False; mode = "packets"; sec = "1"; intro_buf = []; section_heads.setdefault("1", "# 1 · Open")
    if in_pre:
        preamble.append(l); i += 1; continue
    if mode == "0":
        m_b = re.match(r"^\*\*([A-Z])\s*·\s*(.*?)\*\*\s*(.*)$", l)
        if m_b:
            cur_block, cur_block_title = m_b.group(1), m_b.group(2).strip()
            if m_b.group(3).strip() and not lines[i + 1:i + 2] or (m_b.group(3).strip() and not any(x.startswith("- [") for x in lines[i + 1:i + 3])):
                # a block with no boxes: the header is the item (block E)
                work.append([f"{cur_block}1", cur_block, cur_block_title, m_b.group(3).strip(" —"), "camden", "open", "", ""])
            i += 1; continue
        m_i = re.match(r"^- \[( |x|X)\]\s*\*\*([A-Z]\d+)(?:\s*·\s*(.*?))?\*\*\s*(.*)$", l)
        if m_i:
            done = m_i.group(1).lower() == "x"
            wid = m_i.group(2)
            item = (m_i.group(3) or "").strip().rstrip(".")
            text = m_i.group(4).strip()
            # continuation lines
            j = i + 1
            while j < len(lines) and lines[j].startswith("  ") and not lines[j].lstrip().startswith("- ["):
                text += " " + lines[j].strip(); j += 1
            if not item:
                plain = text.replace("**", "")
                cut = re.split(r" · | — |\. ", plain, 1)
                item = cut[0][:90].rstrip(" ,;:")
                text = cut[1] if len(cut) > 1 else ""
            owner = "camden"
            if "agent" in cur_block_title.lower():
                owner = "agent"
            elif "Camden's call" in text or "Camden rules" in text or "your call" in text.lower():
                owner = "camden"
            elif re.search(r"\bAgent\b|agent-side|the agent's", text):
                owner = "agent"
            gate = ""
            work.append([wid, cur_block, cur_block_title, item, owner, "done" if done else "open", gate, text])
            i = j; continue
        i += 1; continue
    if mode == "packets":
        m_p = HEAD.match(l)
        if m_p:
            flush_intro()
            qid, more, title, rest = m_p.group(1), m_p.group(2), m_p.group(3).strip(), m_p.group(4)
            also = " ".join(re.findall(ID, more))
            opened = first_date(rest) or first_date(title)
            rest = re.sub(r"^\s*\*\([^)]*\)\*\s*", "", rest).strip()
            # body until next packet / heading / rule
            j = i + 1; body = [rest] if rest else []
            while j < len(lines) and not HEAD.match(lines[j]) and not re.match(r"^#{1,2}\s", lines[j]) and lines[j].strip() != "---":
                body.append(lines[j]); j += 1
            btxt = "\n".join(body).strip("\n") + "\n"
            if "**ANSWER:**" not in btxt:
                btxt += "\n**ANSWER:**\n>\n>\n"
            if qid not in seen:
                seen.add(qid)
                ask = "one word"
                if re.search(r"\*\*Say[^*]*\*\*", btxt):
                    ask = re.search(r"\*\*Say[^*]*\*\*", btxt).group(0).strip("*").strip()
                questions.append([qid, sec, title.rstrip("."), opened, "open", "camden", ask, "", "", "", "", also])
                bodies[qid] = btxt
            i = j; continue
        intro_buf.append(l); i += 1; continue
    if mode == "closed":
        m_g = re.match(r"^\*\*(\d{4}-\d{2}-\d{2})[a-z]?\s*[—–-]\s*(.*?):?\*\*\s*(.*)$", l)
        if m_g:
            closed_on = m_g.group(1)
            tail = m_g.group(3)
            # prose form: `V-014` → D-223 · `Q-101` → D-224 …
            for m in re.finditer(r"((?:`" + ID + r"`\s*)+)→\s*(closed as moot|D-\d{3}(?:[^·|\n]*?))(?=\s*(?:·|$|\(|—|–|;))", tail):
                ids = re.findall(ID, m.group(1)); closer = m.group(2).strip()
                for qid in ids:
                    if qid not in seen:
                        seen.add(qid); questions.append([qid, "", "", "", "closed", "camden", "", closer.split(" ")[0] if closer.startswith("D-") else closer, closed_on, closer, "", ""])
            if tail.strip():
                logrows.append([closed_on, "", "closed", " ".join(dict.fromkeys(re.findall(ID, tail))), (m_g.group(2) + ": " + tail).replace("**", "")[:400]])
            i += 1; continue
        m_r = re.match(r"^\|\s*`(" + ID + r")`\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$", l)
        if m_r:
            qid, closer, outcome = m_r.groups()
            if qid not in seen:
                seen.add(qid)
                questions.append([qid, "", outcome.strip("*").split("—")[0].strip()[:90], "", "closed", "camden", "", closer, closed_on, outcome, "", ""])
            i += 1; continue
        i += 1; continue
    if mode == "moved":
        m_r = re.match(r"^\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$", l)
        if m_r and re.search(ID, m_r.group(1)):
            for qid in re.findall(ID, m_r.group(1)):
                if qid not in seen:
                    seen.add(qid)
                    questions.append([qid, "", "", "", "moved", "camden", "", m_r.group(2), "", m_r.group(3), "", ""])
        i += 1; continue
    i += 1
if mode == "packets":
    flush_intro()

# the luxury §3 is prose only; engine-swap has no §0 — both handled by the loops above (nothing to do)

QCOLS = ["id", "section", "title", "opened", "status", "owner", "ask", "closer", "closed_on", "outcome", "blocks", "also"]
w(D / "questions.csv", csv_text(QCOLS, questions))
for qid, b in bodies.items():
    w(D / "questions" / f"{qid}.md", b)

# ------------------------------------------------------------------ work.csv (merge with an existing one)
WCOLS = ["id", "block", "block_title", "item", "owner", "state", "gate", "note"]
existing = []
if (D / "work.csv").exists():
    with open(D / "work.csv", encoding="utf-8", newline="") as f:
        rd = csv.DictReader(f)
        for r in rd:
            state = {"moved": "dropped", "closed": "done"}.get(r.get("state", ""), r.get("state", "open")) or "open"
            kind = r.get("kind", "")
            block = {"bring-up": "F", "firmware": "F", "hardware": "H", "design": "X", "docs": "X"}.get(kind, kind[:1].upper() or "X")
            existing.append([r["id"], block, kind, r["item"], "agent", state, r.get("gate", ""), r.get("note", "")])
ids_new = {r[0] for r in work}
merged = work + [r for r in existing if r[0] not in ids_new]
w(D / "work.csv", csv_text(WCOLS, merged))

# ------------------------------------------------------------------ DECISIONS.md
dtext = (P / "DECISIONS.md").read_text(encoding="utf-8")
dlines = dtext.splitlines()
latest_dates = {}
for m in re.finditer(r"\*\*([^*]+)\*\*\s*\((\d{4}-\d{2}-\d{2})[a-z]?\)", dtext.split("\n## ", 1)[0]):
    for i_ in re.findall(ID, m.group(1)):
        latest_dates[i_] = m.group(2)
decisions, dbodies, dsystems, dpreamble = [], {}, [], []
system = ""
i = 0
DHEAD = re.compile(r"^\*\*(" + ID + r")(\([a-z]\))?((?:\s*/\s*" + ID + r"(?:\([a-z)]+\))?)*)\s*[—–-]+\s*(.*?)\*\*(.*)$")
while i < len(dlines):
    l = dlines[i]
    m_s = re.match(r"^##\s+(?:\d+\s*·\s*)?(.*)$", l)
    if m_s:
        system = m_s.group(1).strip()
        if system.lower() != "contents":
            dsystems.append(system)
        i += 1; continue
    m_d = DHEAD.match(l)
    if m_d and system:
        did = m_d.group(1)
        also = " ".join(x for x in re.findall(ID, m_d.group(3)) if x != did)
        title = re.sub(r"\s+", " ", m_d.group(4)).strip().rstrip(".:")
        if len(title) > 72:
            title = title[:72].rsplit(" ", 1)[0].rstrip(",;:—–- ") + "…"
        j = i + 1; body = [l]
        while j < len(dlines) and not DHEAD.match(dlines[j]) and not dlines[j].startswith("## ") and dlines[j].strip() != "---":
            body.append(dlines[j]); j += 1
        btxt = "\n".join(body).rstrip("\n") + "\n"
        n = int(did.split("-")[1])
        own = did.startswith("D-") and LO <= n <= HI
        status = "standing" if own else "inherited"
        date_ = latest_dates.get(did) or first_date(btxt)
        sup = ""
        m_sup = re.search(r"[Ss]upersedes\s+((?:D-\d{3}(?:\([a-z]\))?)(?:\s*(?:,|and|/)\s*D-\d{3})*)", btxt)
        if m_sup and own:
            sup = " ".join(re.findall(ID, m_sup.group(1)))
        if did in dbodies:
            dbodies[did] = dbodies[did].rstrip("\n") + "\n\n" + btxt
            for d in decisions:
                if d[0] == did and also:
                    d[8] = (d[8] + " " + also).strip()
        else:
            decisions.append([did, system, title[:110], date_, status, sup, "", "", also])
            dbodies[did] = btxt
        i = j; continue
    if not system and not l.startswith("**Latest:**"):
        dpreamble.append(l)
    elif system and l.strip() and not l.startswith("|") and system.lower() != "contents":
        # prose inside a system section that is not a decision (luxury Money section) — keep it in the template
        dsystems.append(("prose", system, l))
    i += 1
# superseded rows for anything a standing decision names, when the old id is not itself an entry
have = {d[0] for d in decisions}
for d in list(decisions):
    for old in d[5].split():
        if old not in have and old.startswith("D-"):
            decisions.append([old, d[1], f"(superseded by {d[0]})", "", "superseded", "", d[0], "", ""])
            have.add(old)
DCOLS = ["id", "system", "title", "date", "status", "supersedes", "superseded_by", "closes", "also"]
w(D / "decisions.csv", csv_text(DCOLS, decisions))
for did, b in dbodies.items():
    w(D / "decisions" / f"{did}.md", b)

# closes: a closed question's closer marks the decision
closes = {}
for q in questions:
    if q[4] == "closed" and q[7].startswith("D-"):
        closes.setdefault(q[7], []).append(q[0])
for d in decisions:
    if d[0] in closes:
        d[7] = " ".join(closes[d[0]])
w(D / "decisions.csv", csv_text(DCOLS, decisions))

# ------------------------------------------------------------------ log.csv, project.csv
logrows.sort(key=lambda r: (r[0], r[1]))
LCOLS = ["id", "date", "workflow", "ids", "summary"]
w(D / "log.csv", csv_text(LCOLS, [[f"L{k + 1:03d}", r[0], r[2], r[3], r[4]] for k, r in enumerate(logrows)]))
w(D / "project.csv", csv_text(["key", "value", "note"], [
    ["name", P.name, ""], ["kind", KIND, "electrical · electronics · mechanical · body · software"],
    ["goal", GOAL, ""], ["phase", PHASE, " · ".join(rx7.PHASES)],
    ["opened", {"electrical-build": "2026-08", "luxury-package": "2026-09-02", "engine-swap": "2026-09-02"}[P.name], ""],
    ["range_D", f"{LO}-{HI}", "this project's decision numbers"], ["range_Q", f"{LO}-{HI}", "this project's question numbers"],
    ["range_C", f"{LO}-{HI}", "critique findings"],
]))
if not (D / "retired.csv").exists():
    w(D / "retired.csv", csv_text(["term", "retired_by", "note"], []))

# ------------------------------------------------------------------ templates
pre = "\n".join(preamble).rstrip("\n")
pre = re.sub(r"\n\n\n+", "\n\n", pre)
# drop the first line (title) — the template supplies it
pre_lines = pre.splitlines()
title_line = pre_lines[0] if pre_lines and pre_lines[0].startswith("# ") else "# QUESTIONS"
pre_body = "\n".join(pre_lines[1:]).strip("\n")
sections_md = []
for code in [c for c in section_heads]:
    hl = re.sub(r"^#+\s*", "## ", section_heads[code])
    intro = "\n".join(section_intro.get(code, [])).strip("\n")
    intro = re.sub(r"\n\n\n+", "\n\n", intro)
    sections_md.append(f"{hl}\n\n{intro}\n\n{{{{packets:{code}}}}}\n".replace("\n\n\n", "\n\n"))
q_tpl = f"""<!-- out: QUESTIONS.md -->
{title_line}

{pre_body}

{{{{banners:6}}}}

---

## 0 · The finishing task list

Rendered from `data/work.csv` — every task, who owns it (Camden unless marked *agent*), its state and its gate. `/rx7-plan` works the agent items; the rest are yours.

{{{{work}}}}

---

{chr(10).join(sections_md)}
---

## 3 · Closed

Answered items leave the sections above and land here with their closer (`data/questions.csv`, status `closed`). IDs are permanent and are cited with their closer.

{{{{closed}}}}

---

## 4 · Moved out of this project

{{{{moved}}}}
"""
w(P / "templates" / "QUESTIONS.md", q_tpl)

dpre = "\n".join(dpreamble).strip("\n")
dpre_lines = dpre.splitlines()
dtitle = dpre_lines[0] if dpre_lines and dpre_lines[0].startswith("# ") else "# DECISIONS"
dpre_body = "\n".join(l for l in dpre_lines[1:] if not l.startswith("## Contents") and l.strip() != "---").strip("\n")
dpre_body = re.sub(r"\n\n\n+", "\n\n", dpre_body)
dpre_body = dpre_body.replace("New decisions for this project continue from D-400.", "New decisions for this project continue from {{next_id:D}}.")
sys_md = []
seen_sys = []
for s in dsystems:
    if isinstance(s, tuple):
        continue
    if s in seen_sys:
        continue
    seen_sys.append(s)
    prose = "\n\n".join(x[2] for x in dsystems if isinstance(x, tuple) and x[1] == s)
    sys_md.append(f"## {s}\n\n" + (prose + "\n\n" if prose else "") + f"{{{{decisions:{s}}}}}\n")
d_tpl = f"""<!-- out: DECISIONS.md -->
{dtitle}

{dpre_body}

{{{{latest:14}}}}

## Contents

{' · '.join(seen_sys)}

---

{chr(10).join(sys_md)}"""
w(P / "templates" / "DECISIONS.md", d_tpl)

w(P / "templates" / "LOG.md", f"""<!-- out: LOG.md -->
# LOG — {P.name}

*Rendered from `data/log.csv` — one row per workflow run, newest first. Nothing here is a fact about the design; the facts are in the other tables.*

{{{{log}}}}
""")

# ------------------------------------------------------------------ write
for path, text in out_files.items():
    print(("DRY " if DRY else "wrote ") + str(path.relative_to(ROOT)))
    if not DRY:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
print(f"{len(questions)} questions ({sum(1 for q in questions if q[4]=='open')} open) · {len(decisions)} decisions · {len(merged)} work rows · {len(logrows)} log rows")
