#!/usr/bin/env python3
"""
gen.py — render every derived pin/cavity document from the two data tables.

    02-HARNESS/data/pmu_pins.csv     one row per PMU cavity (39 + the stud)
    02-HARNESS/data/connectors.csv   one row per leg / door / drop cavity
    02-HARNESS/data/housings.csv     one row per housing

Produces (full files):
    02-HARNESS/PIN-MAP.md
    02-HARNESS/CAVITY-STATE.md
    02-HARNESS/diagrams/L1.svg … L4.svg, drops.svg, sill.svg
    03-MODULES/firmware/pmu_sim/channels.h

Refreshes marked blocks inside (everything outside the markers is hand-written):
    01-DESIGN/SPEC.md              <!-- gen:pins --> … <!-- /gen:pins -->
    01-DESIGN/CHANNEL-SCHEDULE.md  <!-- gen:schedule --> … <!-- /gen:schedule -->
    04-BUILD/CUT-LIST.md           <!-- gen:cutlist --> … <!-- /gen:cutlist -->
    02-HARNESS/CONNECTORS.md       <!-- gen:housings --> … <!-- /gen:housings -->

Usage:  python gen.py            (run from anywhere; paths are resolved from this file)
        python gen.py --check    (exit 1 if any output would change — used by check.py)

Edit the CSVs, never the generated tables.  Rule R3: one owner per fact — the
owner of every pin, cavity, colour and estimate is the CSV.
"""
import csv, os, sys, re, io, collections

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.normpath(os.path.join(HERE, "..", ".."))
DATA = os.path.join(PROJ, "02-HARNESS", "data")
CHECK = "--check" in sys.argv
changed = []

def read(name):
    with open(os.path.join(DATA, name), newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

pins = read("pmu_pins.csv")
cavs = read("connectors.csv")
housings = read("housings.csv")

STAMP = "*Generated by `05-PROCESS/tools/gen.py` from `02-HARNESS/data/*.csv` — edit the CSV, not this table.*"

def emit(relpath, text):
    path = os.path.join(PROJ, relpath)
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old == text:
        return
    changed.append(relpath)
    if not CHECK:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)

def replace_block(relpath, tag, body):
    path = os.path.join(PROJ, relpath)
    src = open(path, encoding="utf-8").read()
    start, end = f"<!-- gen:{tag} -->", f"<!-- /gen:{tag} -->"
    if start not in src or end not in src:
        sys.exit(f"{relpath}: missing markers for {tag}")
    pre, rest = src.split(start, 1)
    _, post = rest.split(end, 1)
    new = f"{pre}{start}\n{STAMP}\n\n{body.rstrip()}\n{end}{post}"
    emit(relpath, new)

def md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)

def pinnum(p):
    return 0 if p["pin"] == "STUD" else int(p["pin"])

# ---------------------------------------------------------------- SPEC blocks
def spec_block():
    parts = []
    grp = lambda f: [p for p in pins if f(p)]
    power = grp(lambda p: p["mode"] in ("PWR", "COMM"))
    out25 = grp(lambda p: p["class"] == "25A")
    out15 = grp(lambda p: p["class"] == "15A")
    shared = grp(lambda p: p["class"] == "7A")
    ded = grp(lambda p: p["class"] == "IN")

    parts.append("### 4 · Power, ground and comms\n")
    parts.append(md_table(["Pin", "Name", "Circuit", "AWG", "Colour", "To"],
        [(p["pin"], p["name"], p["circuit"], p["awg"], p["colour"], p["to"]) for p in power]))

    parts.append("\n### 5 · 25 A outputs — 12 AWG, large cavities\n")
    parts.append("Estimates only. Never set a soft fuse from these — the measured column lives in `CHANNEL-SCHEDULE.md`.\n")
    parts.append(md_table(["Pin", "Ch", "Name", "Circuit", "Est. A", "Colour", "To", "Status"],
        [(p["pin"], p["ch"], f"`{p['name']}`", p["circuit"], p["est_a"] or "—", p["colour"], p["to"], p["status"]) for p in out25]))

    parts.append("\n### 6 · 15 A outputs — 14 AWG\n")
    parts.append(md_table(["Pin", "Ch", "Name", "Circuit", "Est. A", "Colour", "To", "Status"],
        [(p["pin"], p["ch"], f"`{p['name']}`", p["circuit"], p["est_a"] or "—", p["colour"], p["to"], p["status"]) for p in out15]))

    parts.append("\n### 7 · 7 A shared pins — 16 AWG\n")
    parts.append("Each of O17–O24 can be an output or an analog input (A9–A16). Six are outputs; O23 and O24 are configured as inputs A15 and A16 — there is no spare on this bank.\n")
    parts.append(md_table(["Pin", "Ch", "Mode", "Name", "Circuit", "Colour", "To", "Status"],
        [(p["pin"], p["ch"], p["mode"], f"`{p['name']}`", p["circuit"], p["colour"], p["to"], p["status"]) for p in shared]))

    parts.append("\n### 8 · Dedicated inputs A1–A8 — 16 AWG\n")
    parts.append("0–5 V, 10-bit. Every switch goes to ground through a finite resistor (D-053), read against the internal 10 kΩ pull-up. Values in `LADDERS.md`.\n")
    parts.append(md_table(["Pin", "In", "Name", "Signal", "Colour", "To", "Status"],
        [(p["pin"], p["ch"], f"`{p['name']}`", p["circuit"], p["colour"], p["to"], p["status"]) for p in ded]))

    n_live = sum(1 for p in pins if p["pin"] != "STUD")
    parts.append(f"\n**{n_live} cavities, all allocated:** 7 power/comms + 10 × 25 A + 6 × 15 A + 8 shared + 8 dedicated. "
                 "Status key: **LIVE** wired and enabled at migration · **PROVISIONED** wire run and capped, hardware fitted empty (D-131) · "
                 "**RESERVED** capped for the LS swap (D-007) · **DEFERRED** conductor allocated, subsystem not designed · **OPEN** a home is still needed.")
    return "\n".join(parts)

# ------------------------------------------------------------- PIN-MAP.md
def pin_map():
    L = ["# PIN MAP — every cavity, box side and leg side", "",
         "*Rev 2026-08-30 · owns: cavity assignments. GENERATED — see the note below.*", "",
         STAMP, "",
         "**This file is the authoritative cavity map** (README conventions). It is generated, so it cannot drift from "
         "`SPEC.md`, `CHANNEL-SCHEDULE.md`, `CUT-LIST.md` or `channels.h` — they all come from the same CSV. "
         "To change a cavity, edit `data/connectors.csv` (leg side) or `data/pmu_pins.csv` (PMU side) and run `gen.py`.", "",
         "Status: **LIVE** · **PROVISIONED** wire run and capped, hardware fitted empty · **RESERVED** LS swap · "
         "**DEFERRED** subsystem not designed yet · **OPEN** needs a PMU pin or fuse position that does not exist yet (see `OPEN.md`) · **SPARE** capped.", "",
         "---", "", "## PMU device connector — 39 cavities, viewed at the device", ""]
    # cavity grid
    bypin = {pinnum(p): p for p in pins if p["pin"] != "STUD"}
    L.append("```")
    for row in range(3):
        cells = []
        for c in range(13):
            n = row * 13 + c + 1
            p = bypin[n]
            cells.append(f"{n:>2}:{p['ch'] if p['ch'] != '—' else p['name'][:5]:<5}")
        L.append("  " + " ".join(cells) + f"   ← row {row+1}")
    L.append("```")
    L.append("Pin 1 top-left, purple lock on the right, connector face toward you (D-139). Large 2.8 mm cavities: 1, 2, 12, 13, 14, 15, 25, 26, 27, 28, 38, 39.")
    L.append("")
    L.append(md_table(["Pin", "Size", "Ch", "Name", "Class", "AWG", "Colour", "Goes to", "Status"],
        [(p["pin"], {"L": "2.8 L", "M": "2.8", "S": "1.5", "stud": "stud"}[p["size"]], p["ch"], f"`{p['name']}`", p["class"], p["awg"], p["colour"], p["to"], p["status"])
         for p in sorted(pins, key=pinnum)]))
    L.append("")
    L.append("---")
    # per connector
    byconn = collections.OrderedDict()
    for c in cavs:
        byconn.setdefault(c["connector"], []).append(c)
    hmeta = {h["code"]: h for h in housings}
    legs = collections.OrderedDict()
    for code in byconn:
        legs.setdefault(hmeta[code]["leg"], []).append(code)
    for leg, codes in legs.items():
        L.append("")
        L.append(f"## {leg}")
        for code in codes:
            h = hmeta[code]
            rows = byconn[code]
            used = sum(1 for r in rows if r["status"] not in ("SPARE",))
            L.append("")
            L.append(f"### {code} · {h['leg_side']} → {h['box_side']} · {len(rows)} cav, {used} used · {h['where']}")
            L.append("")
            if h["note"]:
                L.append(f"*{h['note']}*")
                L.append("")
            L.append(md_table(["Cav", "Circuit", "Source / destination", "AWG", "Colour", "Status", "Note"],
                [(r["cav"], r["circuit"], r["source"], r["awg"], r["colour"], r["status"], r["note"]) for r in rows]))
    # splits
    L.append("")
    L.append("---")
    L.append("")
    L.append("## Pins that feed more than one cavity")
    L.append("")
    L.append("Split at the busbar or the diode strip inside the box, never in a leg.")
    L.append("")
    L.append(md_table(["Pin", "Ch", "Cavities"],
        [(p["pin"], p["ch"] if p["ch"] != "—" else p["name"], p["to"]) for p in pins if " + " in p["to"]]))
    # counts
    L.append("")
    L.append("## Counts")
    L.append("")
    legc = collections.Counter(hmeta[c]["leg"] for c in byconn)
    L.append(md_table(["Group", "Housings (mated pairs)"],
        [("Leg housings L1–L4 (L1-S is two housings)", sum(1 for c in byconn if hmeta[c]["leg"].startswith("L") and "sill" not in hmeta[c]["leg"])),
         ("Door sub-connectors at the sill", sum(1 for c in byconn if "sill" in hmeta[c]["leg"])),
         ("Dash-post drops (ICU, DCU, DIAG, KEY)", sum(1 for c in byconn if hmeta[c]["leg"] == "Drop")),
         ("Lugs (DP-BAT, DP-GND)", 2), ("PMU device connector", 1),
         ("**Total mated pairs**", f"**{len(byconn) + 3}**")]))
    L.append("")
    L.append("A *mated pair* is one plug and its receptacle. Lugs count as pairs; the four dash-post drops are pairs. "
             "Earlier files said 20 and 23 by counting different things, and 14 leg connectors by counting L1-S once — this table is the count.")
    return "\n".join(L) + "\n"

# ----------------------------------------------------------- CAVITY-STATE
def cavity_state():
    L = ["# CAVITY STATE — what is live, provisioned, reserved, deferred or open", "",
         "*Rev 2026-08-30 · owns: nothing — a view over `data/*.csv`. GENERATED.*", "", STAMP, "",
         "The question every later session asks. One line per cavity that is not simply LIVE, then the totals.", "", "---", ""]
    cnt = collections.Counter(c["status"] for c in cavs)
    L.append("## Totals — leg, door and drop cavities")
    L.append("")
    L.append(md_table(["Status", "Cavities"], [(k, cnt[k]) for k in ("LIVE", "PROVISIONED", "RESERVED", "DEFERRED", "OPEN", "SPARE") if cnt[k]] + [("**Total**", f"**{len(cavs)}**")]))
    L.append("")
    pc = collections.Counter(p["status"] for p in pins if p["pin"] != "STUD")
    L.append("## Totals — PMU cavities")
    L.append("")
    L.append(md_table(["Status", "Cavities"], [(k, pc[k]) for k in ("LIVE", "RESERVED") if pc[k]] + [("**Total**", "**39**")]))
    L.append("")
    for status, title in (("OPEN", "OPEN — needs a pin or a fuse position that does not exist yet"),
                          ("PROVISIONED", "PROVISIONED — wire run and capped, hardware fitted empty (D-131)"),
                          ("DEFERRED", "DEFERRED — conductor allocated, subsystem not designed"),
                          ("RESERVED", "RESERVED — LS swap (D-007)"),
                          ("SPARE", "SPARE — capped, no purpose assigned")):
        rows = [c for c in cavs if c["status"] == status]
        if not rows: continue
        L.append(f"## {title}")
        L.append("")
        L.append(md_table(["Connector", "Cav", "Circuit", "Note"], [(c["connector"], c["cav"], c["circuit"], c["note"]) for c in rows]))
        L.append("")
    return "\n".join(L)

# ------------------------------------------------------------ channels.h
def channels_h():
    outs = [p for p in pins if p["ch"].startswith("O") or p["ch"] in ("A15", "A16")]
    order = {}
    for p in outs:
        n = int(p["ch"][1:]) if p["ch"].startswith("O") else {"A15": 23, "A16": 24}[p["ch"]]
        order[n] = p
    enum_names = ["O1_MOTOR", "O2_HEAD_LO", "O3_HEAD_HI", "O4_DEFOG", "O5_FUEL", "O6_TAIL", "O7_BRAKE", "O8_WIPE_LO", "O9_WIPE_HI", "O10_ACC",
                  "O11_HORN", "O12_IGN", "O13_LS_ECU", "O14_LS_FAN", "O15_COMFORT", "O16_BLOWER", "O17_TURN_L", "O18_TURN_R", "O19_REVERSE",
                  "O20_INTERIOR", "O21_START", "O22_KEEPALIVE", "O23_SPARE", "O24_SPARE"]
    def ca(v):
        try: return int(round(float(v) * 100))
        except: return 0
    default_limit = {"25A": 2500, "15A": 1500, "7A": 700}
    rows = []
    for n in range(1, 25):
        p = order[n]
        steady = ca(p["meas_a"] or p["est_a"])
        if p["soft_fuse"] and p["soft_fuse"] not in ("disabled", "from replacement spec"):
            limit = ca(p["soft_fuse"])          # measured soft fuse wins
        elif p["sim_limit"]:
            limit = int(p["sim_limit"])         # explicit provisional value from the CSV
        else:
            limit = max(100, steady * 2)
        if p["meas_a"]: src = "MEASURED"
        elif p["ch"] == "O16": src = "DEAD"
        elif p["status"] == "RESERVED" or p["ch"] in ("A15", "A16"): src = "RESERVED"
        else: src = "EST"
        name = p["name"].replace("_", " ")
        if p["ch"] in ("A15", "A16"): name = f"{p['ch']} IN"
        rows.append((name, steady, limit, int(p["inrush_x10"] or 10), int(p["inrush_ms"] or 0), src, p["ch"], p["note"].split(".")[0][:28]))
    L = ["/*", " * channels.h — PMU channel table for the simulator", " *",
         " * ============================================================",
         " *  GENERATED by 05-PROCESS/tools/gen.py from 02-HARNESS/data/pmu_pins.csv",
         " *  Do not edit here. Put measured figures in the CSV (meas_a / soft_fuse)",
         " *  and re-run gen.py: this file, CHANNEL-SCHEDULE.md, SPEC.md and the",
         " *  PIN-MAP all update together. That is the whole point.",
         " * ============================================================", " *",
         " * Units: 0.01 A, matching CAN 0x130 and cluster_core.h.",
         " * inrush: multiplier x10 applied for inrushMs after switch-on.",
         " * limit:  measured soft fuse where one exists (D-164/165); otherwise a",
         " *         provisional bench value derived from the estimate. The real",
         " *         PMU output stays DISABLED until measured — this table only",
         " *         drives the simulator and the diagnostics page.",
         " */", "", "#ifndef CHANNELS_H", "#define CHANNELS_H", "", "#include <stdint.h>", "",
         "enum ChSrc : uint8_t { EST = 0, MEASURED = 1, DEAD = 2, RESERVED = 3 };", "",
         "struct ChannelSpec {", "    const char *name;", "    uint16_t    steady;      /* 0.01 A                        */",
         "    uint16_t    limit;       /* 0.01 A soft fuse, provisional */", "    uint8_t     inrushX10;   /* multiplier x10 -> 100 = 10.0x */",
         "    uint16_t    inrushMs;", "    ChSrc       src;", "};", "", "/* ---- O1..O24 ---- */", "static const ChannelSpec CH[24] = {",
         "/*  name            steady  limit  inX10   ms   source      */"]
    for name, steady, limit, ix, ims, src, ch, note in rows:
        L.append(f'  {{ "{name}",'.ljust(22) + f"{steady:5},  {limit:5},  {ix:3}, {ims:4}, {src:<8} }}, /* {ch:<4} {note} */")
    L[-1] = L[-1].replace(" }, /*", " }  /*", 1) if False else L[-1]
    L.append("};")
    L.append("")
    L.append("/* Channel indices, so the model reads like the schedule rather than")
    L.append(" * like an array of magic numbers. O23/O24 are configured as inputs A15/A16. */")
    L.append("enum {")
    L.append("  " + ", ".join(enum_names[0:6]) + ",")
    L.append("  " + ", ".join(enum_names[6:12]) + ",")
    L.append("  " + ", ".join(enum_names[12:16]) + ",")
    L.append("  " + ", ".join(enum_names[16:20]) + ",")
    L.append("  " + ", ".join(enum_names[20:24]))
    L.append("};")
    L.append("")
    L.append("/* How many channel currents are still guesses. Printed at boot so the")
    L.append(" * number in front of you is never mistaken for measured data. */")
    L.append("inline int estimatedChannelCount() {")
    L.append("    int n = 0;")
    L.append("    for (int i = 0; i < 24; i++) if (CH[i].src == EST) n++;")
    L.append("    return n;")
    L.append("}")
    L.append("")
    L.append("#endif /* CHANNELS_H */")
    return "\n".join(L) + "\n"

# -------------------------------------------------------- channel schedule
def schedule_block():
    outs = [p for p in pins if p["ch"].startswith("O") or p["ch"] in ("A15", "A16")]
    key = lambda p: int(p["ch"][1:]) if p["ch"].startswith("O") else {"A15": 23, "A16": 24}[p["ch"]]
    rows = []
    for p in sorted(outs, key=key):
        if p["ch"] in ("A15", "A16"):
            rows.append((f"**O{key(p)}**", f"= **{p['ch']}** input — {p['circuit']}", p["class"], p["to"], p["awg"], "—", "*input*", "input", "**n/a**"))
            continue
        meas = f"**{p['meas_a']} MEAS**" if p["meas_a"] else ("*reserved*" if p["status"] == "RESERVED" else ("**motor is DEAD**" if p["ch"] == "O16" else "______"))
        fuse = f"**{p['soft_fuse']}**" if p["soft_fuse"] else "______"
        rows.append((f"**{p['ch']}**", p["circuit"].split(" — ")[0], p["class"], p["to"], p["awg"], p["est_a"] or "—", meas, p["load_type"], fuse))
    measured = sum(1 for p in outs if p["meas_a"])
    body = md_table(["Ch", "Circuit", "Class", "Goes to", "AWG", "EST A", "**MEASURED A**", "Type", "**SOFT FUSE**"], rows)
    body += f"\n\n**{measured} of 22 outputs measured.** The rest are estimates carried since Rev A."
    return body

# --------------------------------------------------------------- cut list
def cutlist_block():
    hmeta = {h["code"]: h for h in housings}
    byleg = collections.OrderedDict()
    for c in cavs:
        byleg.setdefault(hmeta[c["connector"]]["leg"], []).append(c)
    out = []
    for leg, rows in byleg.items():
        out.append(f"### {leg}\n")
        out.append(md_table(["Cavity", "Circuit", "AWG", "Colour", "Status", "Length", "Qty"],
            [(f"{c['connector']} {c['cav']}", c["circuit"], c["awg"], c["colour"], c["status"], "", 1) for c in rows]))
        out.append("")
    out.append("### Inside the box — PMU pin to receptacle\n")
    out.append("One conductor per PMU cavity to its receptacle(s); split at the busbar where a pin feeds more than one.\n")
    out.append(md_table(["PMU pin", "Ch", "AWG", "Colour", "To", "Length", "Qty"],
        [(p["pin"], p["ch"] if p["ch"] != "—" else p["name"], p["awg"], p["colour"], p["to"], "6–18 in", p["to"].count(" + ") + 1) for p in sorted(pins, key=pinnum) if p["pin"] != "STUD"]))
    return "\n".join(out)

# ------------------------------------------------------------- housings
def housings_block():
    rows = []
    for h in housings:
        n = sum(1 for c in cavs if c["connector"] == h["code"])
        used = sum(1 for c in cavs if c["connector"] == h["code"] and c["status"] != "SPARE")
        rows.append((f"**{h['code']}**", h["leg"], h["class"], h["leg_side"], h["box_side"], h["cavities"], used, h["wedgelocks"], h["where"]))
    t = md_table(["Code", "Leg", "Class", "Leg side", "Box side", "Cav", "Used", "Wedgelocks", "Where"], rows)
    legs = sum(1 for h in housings if h["leg"].startswith("L") and "sill" not in h["leg"])
    doors = sum(1 for h in housings if "sill" in h["leg"])
    drops = sum(1 for h in housings if h["leg"] == "Drop")
    t += f"\n\n**{legs} leg housings (14 codes — L1-S is two housings), {doors} door sub-connectors, {drops} dash-post drops** — plus DP-BAT, DP-GND and the PMU device connector: **{len(housings) + 3} mated pairs.** Every housing is Deutsch DT (size 16), DTP (size 12) or DTM (size 20). Order 20 % spare contacts and wedgelocks."
    return t

# ------------------------------------------------------------------ SVG
COL = {"RED": "#c0392b", "ORN": "#d68910", "VIO": "#7d3c98", "GRY": "#5d6d7e", "PNK": "#e91e63", "BLU": "#2471a3", "YEL": "#b7950b", "GRN": "#1e8449", "BLK": "#212121"}
def colour_of(c):
    base = c.split("/")[0].strip()
    return COL.get(base, "#7f8c8d")

def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def leg_svg(title, codes, subtitle=""):
    hmeta = {h["code"]: h for h in housings}
    rowsH = 20
    W = 1180
    y = 70
    items = []   # (connector, cav row dict, y)
    blocks = []
    for code in codes:
        rows = [c for c in cavs if c["connector"] == code]
        h = hmeta[code]
        blocks.append((code, h, y, rows))
        y += 28 + rowsH * len(rows) + 22
    H = y + 30
    # sources on the left: PMU pins, relays, fuses, drops
    srcs = collections.OrderedDict()
    for code, h, y0, rows in blocks:
        for i, r in enumerate(rows):
            src = r["source"]
            key = src
            m = re.match(r"^(O\d+|A\d+|CAN\dH|CAN\dL|\+5V|K\d+(?:/K\d+)?|Busbar[^,]*|DP-GND|DP-ICU \d+|L\d-S\d \d+|L3-S2 \d+|pass-through.*|Sill.*|Mirror control.*|Diode strip.*|NO (?:PIN|OUTPUT).*|A6 ladder.*|capped|—)", src)
            key = m.group(1) if m else src
            if key in ("capped", "—"): continue
            srcs.setdefault(key, []).append((y0 + 28 + i * rowsH + rowsH / 2, r))
    # order sources: PMU pins by number then others
    def skey(k):
        m = re.match(r"^([OA])(\d+)$", k)
        if m: return (0 if m.group(1) == "O" else 1, int(m.group(2)))
        return (2, k)
    sorted_srcs = sorted(srcs.keys(), key=skey)
    S = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" font-family="ui-monospace, Menlo, Consolas, monospace" font-size="11">',
         '<style>.t{fill:#1b1b1b}.d{fill:#5d6d7e}.h{font-weight:700;fill:#1b1b1b}.box{fill:#fff;stroke:#1b1b1b;stroke-width:1.2}.src{fill:#f4f6f6;stroke:#5d6d7e}</style>',
         f'<rect width="{W}" height="{H}" fill="#fbfbf9"/>',
         f'<text x="20" y="30" font-size="18" class="h">{esc(title)}</text>',
         f'<text x="20" y="48" class="d">{esc(subtitle)} · generated from data/connectors.csv · dashed = provisioned / deferred / reserved · grey = open or spare</text>']
    # source column
    sy = 70
    src_y = {}
    for k in sorted_srcs:
        ys = [t[0] for t in srcs[k]]
        cy = sum(ys) / len(ys)
        # keep sources in order without overlap
        cy = max(cy, sy)
        src_y[k] = cy
        sy = cy + 18
        S.append(f'<rect x="20" y="{cy-9}" width="150" height="18" rx="3" class="src"/>')
        S.append(f'<text x="26" y="{cy+4}" class="t">{esc(k[:22])}</text>')
    if sy > H:
        H2 = sy + 20
        S[0] = S[0].replace(f'height="{H}"', f'height="{H2}"').replace(f'0 0 {W} {H}"', f'0 0 {W} {H2}"')
        S[2] = f'<rect width="{W}" height="{H2}" fill="#fbfbf9"/>'
    # connector blocks
    for code, h, y0, rows in blocks:
        bw = 760
        bx = 380
        S.append(f'<rect x="{bx}" y="{y0}" width="{bw}" height="{28 + rowsH*len(rows)}" rx="4" class="box"/>')
        S.append(f'<rect x="{bx}" y="{y0}" width="{bw}" height="24" fill="#1b1b1b"/>')
        S.append(f'<text x="{bx+8}" y="{y0+16}" fill="#fff" font-weight="700">{esc(code)}</text>')
        S.append(f'<text x="{bx+110}" y="{y0+16}" fill="#ddd">{esc(h["leg_side"])} → {esc(h["box_side"])} · {len(rows)} cav · {esc(h["where"])}</text>')
        for i, r in enumerate(rows):
            ry = y0 + 28 + i * rowsH
            cy = ry + rowsH / 2
            dashed = r["status"] in ("PROVISIONED", "DEFERRED", "RESERVED")
            grey = r["status"] in ("OPEN", "SPARE")
            stroke = "#aab" if grey else colour_of(r["colour"])
            S.append(f'<text x="{bx+8}" y="{cy+4}" class="h">{r["cav"]}</text>')
            S.append(f'<text x="{bx+36}" y="{cy+4}" class="t">{esc(r["circuit"][:58])}</text>')
            S.append(f'<text x="{bx+470}" y="{cy+4}" class="d">{esc(r["awg"])} {esc(r["colour"])}</text>')
            S.append(f'<text x="{bx+600}" y="{cy+4}" class="d">{esc(r["status"])}</text>')
            # wire from source
            src = r["source"]
            m = re.match(r"^(O\d+|A\d+|CAN\dH|CAN\dL|\+5V|K\d+(?:/K\d+)?|Busbar[^,]*|DP-GND|DP-ICU \d+|L\d-S\d \d+|L3-S2 \d+|pass-through.*|Sill.*|Mirror control.*|Diode strip.*|NO (?:PIN|OUTPUT).*|A6 ladder.*|capped|—)", src)
            k = m.group(1) if m else src
            if k in src_y and k not in ("capped", "—"):
                x0, y0s = 170, src_y[k]
                sw = 2 if r["awg"].startswith("12") else 1.4
                dash = ' stroke-dasharray="6 4"' if dashed else ""
                S.append(f'<path d="M{x0},{y0s} C {x0+90},{y0s} {bx-90},{cy} {bx},{cy}" fill="none" stroke="{stroke}" stroke-width="{sw}"{dash}/>')
    S.append("</svg>")
    return "\n".join(S) + "\n"

# ------------------------------------------------------------------ run
spec = spec_block()
replace_block(os.path.join("01-DESIGN", "SPEC.md"), "pins", spec)
replace_block(os.path.join("01-DESIGN", "CHANNEL-SCHEDULE.md"), "schedule", schedule_block())
replace_block(os.path.join("04-BUILD", "CUT-LIST.md"), "cutlist", cutlist_block())
replace_block(os.path.join("02-HARNESS", "CONNECTORS.md"), "housings", housings_block())
emit(os.path.join("02-HARNESS", "PIN-MAP.md"), pin_map())
emit(os.path.join("02-HARNESS", "CAVITY-STATE.md"), cavity_state())
emit(os.path.join("03-MODULES", "firmware", "pmu_sim", "channels.h"), channels_h())
emit(os.path.join("02-HARNESS", "diagrams", "L1-engine.svg"), leg_svg("L1 · ENGINE leg", ["L1-P", "L1-S1", "L1-S2"], "Firewall grommet boundary"))
emit(os.path.join("02-HARNESS", "diagrams", "L2-front-chassis.svg"), leg_svg("L2 · FRONT CHASSIS leg", ["L2-P1", "L2-P2", "L2-M", "L2-S"], "Firewall / radiator support boundary"))
emit(os.path.join("02-HARNESS", "diagrams", "L3-dash.svg"), leg_svg("L3 · DASH leg", ["L3-P", "L3-M", "L3-S1", "L3-S2", "L3-S3"], "Dash structure boundary"))
emit(os.path.join("02-HARNESS", "diagrams", "L4-rear-cabin.svg"), leg_svg("L4 · REAR CABIN leg", ["L4-P", "L4-M", "L4-S"], "Tunnel entry boundary"))
emit(os.path.join("02-HARNESS", "diagrams", "sill-doors.svg"), leg_svg("SILL NODE · door connectors D1 / D2", ["D1", "D2"], "Sub-node of L4"))
emit(os.path.join("02-HARNESS", "diagrams", "dash-post-drops.svg"), leg_svg("DASH POST · module and port drops", ["DP-ICU", "DP-DCU", "DP-DIAG", "DP-KEY"], "Box-adjacent, not part of any leg"))

if CHECK:
    if changed:
        print("gen.py --check: OUT OF DATE →", ", ".join(changed))
        sys.exit(1)
    print("gen.py --check: all generated outputs are current")
else:
    print("gen.py: wrote", len(changed), "file(s):", ", ".join(changed) if changed else "nothing changed")
